del apigo.log
del *.api
del metric.dat
del metric.det
del auxiliary.txt

path=C:\CoreProjects\parser\bin;%path%

qtp rmaBilling checkf002tech_serv_date.pre checkf002tech_serv_date.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing1.pre costing1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing1_noweb.pre costing1_noweb.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing2.pre costing2.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing2_noweb.pre costing2_noweb.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing3.pre costing3.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing4.pre costing4.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing5.pre costing5.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing5_noweb.pre costing5_noweb.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing6_man_rej_dtl.pre costing6_man_rej_dtl.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing6_noweb.pre costing6_noweb.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling costing7.pre costing7.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling create_dummy_records.pre create_dummy_records.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling docrevall.pre docrevall.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling f020_info_import.pre f020_info_import.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling f050_bi.pre f050_bi.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling f050_csv.pre f050_csv.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling f050ma1.pre f050ma1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling fix_adj_claim_file_1.pre fix_adj_claim_file_1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling fix_adj_claim_file_2.pre fix_adj_claim_file_2.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling fix_dump_tech.pre fix_dump_tech.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling fix_f001_f002_all.pre fix_f001_f002_all.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling fix_seq_nbrs.pre fix_seq_nbrs.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling maria_rejects1.pre maria_rejects1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling maria_rejects2.pre maria_rejects2.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling newu701.pre newu701.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling prodtithe.pre prodtithe.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling purge_f050_f051.pre purge_f050_f051.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r005_csv.pre r005_csv.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r120.pre r120.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r121_summ.pre r121_summ.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r128a.pre r128a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r136.pre r136.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r138_csv.pre r138_csv.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r139_csv.pre r139_csv.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r140_a1.pre r140_a1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r140w1.pre r140w1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling r140w2.pre r140w2.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling solo_earnings.pre solo_earnings.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling solo_income_summary.pre solo_income_summary.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling solotithe.pre solotithe.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling suspend_agent_detail.pre suspend_agent_detail.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling suspend_dtl.pre suspend_dtl.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling suspend_dtl2.pre suspend_dtl2.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling temp_ignore_agent6_susp_hdr.pre temp_ignore_agent6_susp_hdr.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u010daily.pre u010daily.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u014_f050.pre u014_f050.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u015.pre u015.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u016.pre u016.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u020_shdw.pre u020_shdw.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u020a.pre u020a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u020b.pre u020b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u020c.pre u020c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u020d.pre u020d.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u021a.pre u021a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u021f.pre u021f.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u022a1.pre u022a1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u022b.pre u022b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u022c.pre u022c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030_dtl_tech_prof.pre u030_dtl_tech_prof.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030b_1.pre u030b_1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030b_60.pre u030b_60.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030b_autoadj_clinic_dtl.pre u030b_autoadj_clinic_dtl.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030b_part1.pre u030b_part1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030b_part3_a.pre u030b_part3_a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030b_part3_b.pre u030b_part3_b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030bb.pre u030bb.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u030bb_1.pre u030bb_1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u031.pre u031.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u035a.pre u035a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u085.pre u085.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u085b.pre u085b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u085c.pre u085c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u085d.pre u085d.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u085e.pre u085e.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u086.pre u086.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u086a.pre u086a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u090.pre u090.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u090f.pre u090f.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u093.pre u093.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u095.pre u095.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u100.pre u100.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u105.pre u105.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u110_1.pre u110_1.api /cc=rma /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u110_2.pre u110_2.api /cc=rma /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u110b_rma.pre u110b_rma.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u111c.pre u111c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u112.pre u112.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u113.pre u113.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u114a.pre u114a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u114b.pre u114b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u115_debug.pre u115_debug.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u115_debug_f119.pre u115_debug_f119.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u115a.pre u115a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u115b.pre u115b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u115b_debug.pre u115b_debug.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u115c.pre u115c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u117.pre u117.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u118.pre u118.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u119.pre u119.api /cc=rma /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u119b.pre u119b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u121.pre u121.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u122.pre u122.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u122b.pre u122b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u125.pre u125.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u126.pre u126.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u127.pre u127.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u130.pre u130.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u131a.pre u131a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u132_dc.pre u132_dc.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u132_sp.pre u132_sp.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_a.pre u140_a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_b.pre u140_b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_c.pre u140_c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_d.pre u140_d.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_d1_remove_dups.pre u140_d1_remove_dups.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_e.pre u140_e.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u140_f.pre u140_f.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u141a.pre u141a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u141c.pre u141c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u704.pre u704.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u704a.pre u704a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u705.pre u705.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u708.pre u708.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u716a.pre u716a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u716c.pre u716c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u802.pre u802.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u901.pre u901.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u920.pre u920.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u921a.pre u921a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u921c.pre u921c.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling u997.pre u997.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling unlof002_me_claim.pre unlof002_me_claim.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling unlof002_rat_payment.pre unlof002_rat_payment.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0012b.pre utl0012b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0012d.pre utl0012d.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0017.pre utl0017.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0018.pre utl0018.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0018a.pre utl0018a.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0018b.pre utl0018b.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0021.pre utl0021.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0025.pre utl0025.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0030.pre utl0030.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0100.pre utl0100.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0119.pre utl0119.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0200.pre utl0200.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0201.pre utl0201.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0201_f119.pre utl0201_f119.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling utl0f020_ohip_sin.pre utl0f020_ohip_sin.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling web_before_after.pre web_before_after.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling webpatients_doc.pre webpatients_doc.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling yearend_1.pre yearend_1.api /METRIC=metric.dat /LOG=apigo.log
qtp rmaBilling yearend_2.pre yearend_2.api /METRIC=metric.dat /LOG=apigo.log
