*
*
*

01  TAPEOUT-CLMHDR2-REC.

    05  TAPEOUT-CLMHDR-VALUE-HER		PIC X(3).	
    05  TAPEOUT-CLMHDR-PAT-OHIP-NBR		PIC X(12).
    05  TAPEOUT-CLMHDR-PAT-SURNAME		PIC X(9).
    05  TAPEOUT-CLMHDR-GIVEN-NAME		PIC X(5).
    05  TAPEOUT-CLMHDR-SEX			PIC 9.
    05  TAPEOUT-CLMHDR-PROV-CD			PIC X(2).
    05  FILLER					PIC X(31).
    05  TAPEOUT-CLMHDR-LOC-CODE			PIC X(4).
    05  TAPEOUT-CLMHDR-AGENT-CD			PIC X.
    05  TAPEOUT-CLMHDR-I-O-IND			PIC X.
    05  TAPEOUT-CLMHDR-PHONE-NO			PIC X(10).

