USE [%DatabaseName%]

/****** Object:  Table [SEQUENTIAL].[ADJ_CLAIM_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[ADJ_CLAIM_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[ADJ_CLAIM_FILE]
END
CREATE TABLE [SEQUENTIAL].[ADJ_CLAIM_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[ADJ_BATCH_NBR] [varchar](8) NULL,
	[ADJ_CLAIM_NBR] [numeric](2, 0) NULL,
	[ADJ_OMA_CD_SUFF] [varchar](5) NULL,
	[ADJ_SERV_DATE] [numeric](8, 0) NULL,
	[ADJ_AGENT_CD] [numeric](1, 0) NULL,
	[ADJ_PAT_ACRONYM] [varchar](9) NULL,
	[ADJ_AMT_BAL] [numeric](7, 0) NULL,
	[ADJ_DIAG_CD] [numeric](3, 0) NULL,
	[ADJ_LINE_NO] [numeric](2, 0) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[AFP_A1F_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A1F_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[AFP_A1F_FILE]
END
CREATE TABLE [SEQUENTIAL].[AFP_A1F_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[AFP_TRANSACTION_ID] [varchar](2) NULL,
	[AFP_RECORD_ID] [varchar](1) NULL,
	[FILLER_1] [varchar](1) NULL,
	[AFP_GOVERNANCE_GROUP] [varchar](4) NULL,
	[FILLER_2] [varchar](6) NULL,
	[AFP_GROUP_NAME] [varchar](75) NULL,
	[AFP_PAYMENT_SIGN] [varchar](1) NULL,
	[AFP_PAYMENT_AMT] [numeric](11, 0) NULL,
	[FILLER_3] [varchar](5) NULL,
	[AFP_REPORTING_MTH] [varchar](6) NULL,
	[AFP_RELEASE_ID] [varchar](3) NULL,
	[FILLER_4] [varchar](19) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[AFP_A2G_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A2G_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[AFP_A2G_FILE]
END
CREATE TABLE [SEQUENTIAL].[AFP_A2G_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[AFP_TRANSACTION_ID] [varchar](2) NULL,
	[AFP_RECORD_ID] [varchar](1) NULL,
	[FILLER_1] [varchar](1) NULL,
	[DOC_AFP_PAYM_GROUP] [varchar](4) NULL,
	[FILLER_2] [varchar](6) NULL,
	[AFP_GROUP_NAME] [varchar](75) NULL,
	[AFP_PAYMENT_SIGN] [varchar](1) NULL,
	[AFP_PAYMENT_AMT] [numeric](11, 0) NULL,
	[AFP_PAYMENT_PERCENTAGE] [numeric](5, 0) NULL,
	[AFP_SUBMISSION_SIGN] [varchar](1) NULL,
	[AFP_SUBMISSION_AMT] [numeric](11, 0) NULL,
	[FILLER_3] [varchar](16) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[AFP_A2S_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A2S_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[AFP_A2S_FILE]
END
CREATE TABLE [SEQUENTIAL].[AFP_A2S_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[AFP_TRANSACTION_ID] [varchar](2) NULL,
	[AFP_RECORD_ID] [varchar](1) NULL,
	[FILLER_1] [varchar](1) NULL,
	[DOC_AFP_PAYM_GROUP] [varchar](4) NULL,
	[DOC_AFP_PAYM_SOLO] [varchar](6) NULL,
	[AFP_SOLO_NAME] [varchar](75) NULL,
	[AFP_CONVERSION_SIGN] [varchar](1) NULL,
	[AFP_CONVERSION_AMT] [numeric](11, 0) NULL,
	[AFP_PAYMENT_PERCENTAGE] [numeric](5, 0) NULL,
	[AFP_SUBMISSION_SIGN] [varchar](1) NULL,
	[AFP_SUBMISSION_AMT] [numeric](11, 0) NULL,
	[FILLER_3] [varchar](16) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[AFP_A3C_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A3C_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[AFP_A3C_FILE]
END
CREATE TABLE [SEQUENTIAL].[AFP_A3C_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[AFP_TRANSACTION_ID] [varchar](2) NULL,
	[AFP_RECORD_ID] [varchar](1) NULL,
	[FILLER_1] [varchar](86) NULL,
	[AFP_PAYMENT_SIGN] [varchar](1) NULL,
	[AFP_PAYMENT_AMT] [numeric](11, 0) NULL,
	[FILLER_3] [varchar](34) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[AFP_A4T_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A4T_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[AFP_A4T_FILE]
END
CREATE TABLE [SEQUENTIAL].[AFP_A4T_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[AFP_TRANSACTION_ID] [varchar](2) NULL,
	[AFP_RECORD_ID] [varchar](1) NULL,
	[FILLER_1] [varchar](86) NULL,
	[AFP_PAYMENT_SIGN] [varchar](1) NULL,
	[AFP_PAYMENT_AMT] [numeric](11, 0) NULL,
	[FILLER_3] [varchar](34) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[BATHDR_REC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[BATHDR_REC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[BATHDR_REC]
END
CREATE TABLE [SEQUENTIAL].[BATHDR_REC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[BATHDR_TRANS_ID] [varchar](2) NULL,
	[BATHDR_REC_ID] [varchar](1) NULL,
	[BATHDR_RELEASE_ID] [varchar](3) NULL,
	[BATHDR_MOH_CD] [varchar](1) NULL,
	[BATHDR_BATCH_ID] [numeric](12, 0) NULL,
	[BATHDR_OPER_NUM] [numeric](6, 0) NULL,
	[BATHDR_GROUP_NUM] [varchar](4) NULL,
	[BATHDR_PROVIDER_NUM] [numeric](6, 0) NULL,
	[BATHDR_SPECIALTY_CD] [numeric](2, 0) NULL,
	[BATHDR_FILLER] [varchar](30) NULL,
	[BATHDR_DEF_BATCH_I_O_IND] [varchar](1) NULL,
	[BATHDR_DEF_BATCH_LOCATION] [varchar](4) NULL,
	[BATHDR_CLINIC_1_2] [numeric](2, 0) NULL,
	[BATHDR_DEPT] [numeric](2, 0) NULL,
	[BATHDR_DOC_NBR] [varchar](3) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[CHECKSUM_IDS]    Script Date: 5/25/2017 5:17:13 PM ******/
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CHECKSUM_IDS]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[CHECKSUM_IDS]
END
CREATE TABLE [SEQUENTIAL].[CHECKSUM_IDS](
	[ID] [int] NULL,
	[NEXTVAL] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

/****** Object:  Table [SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE]
END
CREATE TABLE [SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMDTL_ID] [varchar](16) NULL,
	[CLMDTL_NBR_SERV] [numeric](2, 0) NULL,
	[CLMDTL_SV_DATE] [varchar](8) NULL,
	[CLMDTL_CONSEC_DATES] [numeric](9, 0) NULL,
	[CLMDTL_SV_NBR1] [numeric](1, 0) NULL,
	[CLMDTL_SV_NBR2] [numeric](1, 0) NULL,
	[CLMDTL_SV_NBR3] [numeric](1, 0) NULL,
	[CLMDTL_SV_DAY1] [numeric](2, 0) NULL,
	[CLMDTL_SV_DAY2] [numeric](2, 0) NULL,
	[CLMDTL_SV_DAY3] [numeric](2, 0) NULL,
	[CLMDTL_AMT_TECH_BILLED] [numeric](6, 0) NULL,
	[CLMDTL_FEE_OMA] [numeric](7, 0) NULL,
	[CLMDTL_FEE_OHIP] [numeric](7, 0) NULL,
	[CLMDTL_DATE_PERIOD_END] [varchar](8) NULL,
	[CLMHDR_HOSP] [varchar](1) NULL,
	[CLMHDR_DOC_DEPT] [numeric](2, 0) NULL,
	[CLMHDR_AGENT_CD] [numeric](1, 0) NULL,
	[CLMHDR_PAT_OHIP_ID_OR_CHART] [varchar](16) NULL,
	[CLMHDR_LOC] [varchar](4) NULL,
	[CLMHDR_REFER_DOC_NBR] [numeric](6, 0) NULL,
	[CLMHDR_DIAG_CD] [numeric](3, 0) NULL,
	[CLMHDR_DOC_SPEC_CD] [numeric](2, 0) NULL,
	[CLMHDR_I_O_PAT_IND] [varchar](1) NULL,
	[CLMHDR_DATE_ADMIT] [varchar](8) NULL,
	[CLMHDR_DOC_NBR_OHIP] [numeric](6, 0) NULL,
	[PAT_OHIP_MMYY] [varchar](15) NULL,
	[PAT_CHART_NBR] [varchar](10) NULL,
	[PAT_CHART_NBR_2] [varchar](10) NULL,
	[PAT_CHART_NBR_3] [varchar](10) NULL,
	[PAT_CHART_NBR_4] [varchar](10) NULL,
	[PAT_CHART_NBR_5] [varchar](11) NULL,
	[PAT_HEALTH_NBR] [numeric](10, 0) NULL,
	[PAT_VERSION_CD] [varchar](2) NULL,
	[PAT_PROV_CD] [varchar](2) NULL,
	[PAT_BIRTH_DATE] [numeric](8, 0) NULL,
	[PAT_SEX] [varchar](1) NULL,
	[PAT_SURNAME] [varchar](25) NULL,
	[PAT_GIVEN_NAME] [varchar](17) NULL,
	[PAT_INIT] [varchar](3) NULL,
	[PAT_PHONE_NBR] [varchar](20) NULL,
	[SUBSCR_ADDR1] [varchar](30) NULL,
	[SUBSCR_ADDR2] [varchar](30) NULL,
	[SUBSCR_ADDR3] [varchar](30) NULL,
	[SUBSCR_PROV_CD] [varchar](2) NULL,
	[SUBSCR_POSTAL_CD] [varchar](10) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[CLAIMS_WORK_MSTR]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLAIMS_WORK_MSTR]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[CLAIMS_WORK_MSTR]
END
CREATE TABLE [SEQUENTIAL].[CLAIMS_WORK_MSTR](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DEPT_NBR] [numeric](2, 0) NULL,
	[APPTI_FD_RECORD_STATUS] [varchar](1) NULL,
	[AGENT_CD] [numeric](1, 0) NULL,
	[ADJ_AGENT_CD] [numeric](1, 0) NULL,
	[CLMHDR_PAT_ACRONYM] [varchar](9) NULL,
	[FILLER_BRAD1] [varchar](15) NULL,
	[CLAIM_NBR_BRAD] [varchar](10) NULL,
	[OHIP_STATUS] [varchar](2) NULL,
	[FILLER_BRAD2] [varchar](1) NULL,
	[FEE_OMA] [numeric](8, 0) NULL,
	[FEE_OHIP] [numeric](8, 0) NULL,
	[FEE_PAID] [numeric](8, 0) NULL,
	[FEE_DUE] [numeric](8, 0) NULL,
	[PED] [numeric](8, 0) NULL,
	[SERVICE_DATE] [varchar](6) NULL,
	[FILLER_BRAD3] [varchar](22) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[CLMHDR_1_REC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLMHDR_1_REC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[CLMHDR_1_REC]
END
CREATE TABLE [SEQUENTIAL].[CLMHDR_1_REC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_1_TRANS_ID] [varchar](2) NULL,
	[CLMHDR_1_REC_ID] [varchar](1) NULL,
	[CLMHDR_1_HEALTH_NUM] [varchar](10) NULL,
	[CLMHDR_1_VERSION_CD] [varchar](2) NULL,
	[CLMHDR_1_BIRTH_DATE] [numeric](8, 0) NULL,
	[CLMHDR_1_ACCOUNT_NUM] [varchar](8) NULL,
	[CLMHDR_1_PAYMENT_PRG] [varchar](3) NULL,
	[CLMHDR_1_PAYEE] [varchar](1) NULL,
	[CLMHDR_1_REF_DOC_NUM] [numeric](6, 0) NULL,
	[CLMHDR_1_HOSP_NUM] [numeric](4, 0) NULL,
	[CLMHDR_1_ADMIT_DATE] [numeric](8, 0) NULL,
	[CLMHDR_1_REF_LAB_NUM] [numeric](4, 0) NULL,
	[CLMHDR_1_MAN_REV_IND] [varchar](1) NULL,
	[CLMHDR_1_LOC_CODE] [varchar](4) NULL,
	[CLMHDR_1_FILLER] [varchar](17) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[CLMHDR_2_REC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLMHDR_2_REC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[CLMHDR_2_REC]
END
CREATE TABLE [SEQUENTIAL].[CLMHDR_2_REC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_2_TRANS_ID] [varchar](2) NULL,
	[CLMHDR_2_REC_ID] [varchar](1) NULL,
	[CLMHDR_2_OHIP_NUM] [varchar](12) NULL,
	[CLMHDR_2_PAT_SURNAME] [varchar](9) NULL,
	[CLMHDR_2_GIVEN_NAME] [varchar](5) NULL,
	[CLMHDR_2_PAT_SEX] [numeric](1, 0) NULL,
	[CLMHDR_2_PROV_CD] [varchar](2) NULL,
	[CLMHDR_2_FILLER] [varchar](30) NULL,
	[CLMHDR_2_CONFIDENTIALITY_FLAG] [varchar](1) NULL,
	[CLMHDR_2_LOC_CODE] [varchar](4) NULL,
	[CLMHDR_2_AGENT_CD] [varchar](1) NULL,
	[CLMHDR_2_I_O_IND] [varchar](1) NULL,
	[CLMHDR_2_PHONE_NO] [varchar](10) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F002_DTL_AFTER]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F002_DTL_AFTER]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F002_DTL_AFTER]
END
CREATE TABLE [SEQUENTIAL].[F002_DTL_AFTER](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[BATCTRL_BATCH_STATUS] [varchar](1) NULL,
	[BATCTRL_BATCH_TYPE] [varchar](1) NULL,
	[BATCTRL_ADJ_CD] [varchar](1) NULL,
	[CLMHDR_CLINIC_NBR_1_2] [numeric](2, 0) NULL,
	[CLMHDR_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_CLAIM_NBR] [numeric](2, 0) NULL,
	[CLMHDR_DOC_NBR] [varchar](3) NULL,
	[CLMHDR_DOC_DEPT] [int] NULL,
	[CLMHDR_LOC] [varchar](4) NULL,
	[CLMHDR_AGENT_CD] [int] NULL,
	[CLMHDR_MANUAL_AND_TAPE_PAYMENTS] [int] NULL,
	[CLMHDR_AMT_TECH_PAID] [int] NULL,
	[CLMHDR_I_O_PAT_IND] [varchar](1) NULL,
	[CLMHDR_ADJ_CD_SUB_TYPE] [varchar](1) NULL,
	[CLMHDR_ADJ_CD] [varchar](1) NULL,
	[CLMHDR_PAYROLL] [varchar](1) NULL,
	[CLMDTL_OMA_CD] [varchar](4) NULL,
	[CLMDTL_OMA_SUFF] [varchar](1) NULL,
	[CLMDTL_FEE_OHIP] [int] NULL,
	[CLMDTL_NBR_SERV] [numeric](2, 0) NULL,
	[CLMDTL_AMT_TECH_BILLED] [int] NULL,
	[CLMDTL_DATE_PERIOD_END] [varchar](8) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F002_DTL_BEFORE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F002_DTL_BEFORE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F002_DTL_BEFORE]
END
CREATE TABLE [SEQUENTIAL].[F002_DTL_BEFORE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[BATCTRL_BATCH_STATUS] [varchar](1) NULL,
	[BATCTRL_BATCH_TYPE] [varchar](1) NULL,
	[BATCTRL_ADJ_CD] [varchar](1) NULL,
	[CLMHDR_CLINIC_NBR_1_2] [numeric](2, 0) NULL,
	[CLMHDR_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_CLAIM_NBR] [numeric](2, 0) NULL,
	[CLMHDR_DOC_NBR] [varchar](3) NULL,
	[CLMHDR_DOC_DEPT] [int] NULL,
	[CLMHDR_LOC] [varchar](4) NULL,
	[CLMHDR_AGENT_CD] [int] NULL,
	[CLMHDR_MANUAL_AND_TAPE_PAYMENTS] [int] NULL,
	[CLMHDR_AMT_TECH_PAID] [int] NULL,
	[CLMHDR_I_O_PAT_IND] [varchar](1) NULL,
	[CLMHDR_ADJ_CD_SUB_TYPE] [varchar](1) NULL,
	[CLMHDR_ADJ_CD] [varchar](1) NULL,
	[CLMHDR_PAYROLL] [varchar](1) NULL,
	[CLMDTL_OMA_CD] [varchar](4) NULL,
	[CLMDTL_OMA_SUFF] [varchar](1) NULL,
	[CLMDTL_FEE_OHIP] [int] NULL,
	[CLMDTL_NBR_SERV] [numeric](2, 0) NULL,
	[CLMDTL_AMT_TECH_BILLED] [int] NULL,
	[CLMDTL_DATE_PERIOD_END] [varchar](8) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F020_DOCTOR_AUDIT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F020_DOCTOR_AUDIT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F020_DOCTOR_AUDIT]
END
CREATE TABLE [SEQUENTIAL].[F020_DOCTOR_AUDIT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NOT NULL,
	[DOC_DEPT] [numeric](2, 0) NULL,
	[DOC_OHIP_NBR] [numeric](6, 0) NULL,
	[DOC_SIN_NBR] [numeric](9, 0) NULL,
	[DOC_SPEC_CD] [numeric](2, 0) NULL,
	[DOC_HOSP_NBR] [varchar](4) NULL,
	[DOC_NAME] [varchar](24) NULL,
	[DOC_NAME_SOUNDEX] [varchar](4) NULL,
	[DOC_INITS] [varchar](3) NULL,
	[DOC_FULL_PART_IND] [varchar](1) NULL,
	[DOC_BANK_NBR] [numeric](4, 0) NULL,
	[DOC_BANK_BRANCH] [numeric](5, 0) NULL,
	[DOC_BANK_ACCT] [varchar](12) NULL,
	[DOC_DATE_FAC_START] [numeric](8, 0) NULL,
	[DOC_DATE_FAC_TERM] [numeric](8, 0) NULL,
	[DOC_YTDGUA] [numeric](9, 0) NULL,
	[DOC_YTDGUB] [numeric](9, 0) NULL,
	[DOC_YTDGUC] [numeric](9, 0) NULL,
	[DOC_YTDGUD] [numeric](9, 0) NULL,
	[DOC_YTDCEA] [numeric](9, 0) NULL,
	[DOC_YTDCEX] [numeric](9, 0) NULL,
	[DOC_YTDEAR] [numeric](9, 0) NULL,
	[DOC_YTDINC] [numeric](9, 0) NULL,
	[DOC_YTDEFT] [numeric](9, 0) NULL,
	[DOC_TOTINC_G] [numeric](9, 0) NULL,
	[DOC_EP_DATE_DEPOSIT] [numeric](8, 0) NULL,
	[DOC_TOTINC] [numeric](9, 0) NULL,
	[DOC_EP_CEIEXP] [numeric](9, 0) NULL,
	[DOC_ADJCEA] [numeric](9, 0) NULL,
	[DOC_ADJCEX] [numeric](9, 0) NULL,
	[DOC_CEICEA] [numeric](9, 0) NULL,
	[DOC_CEICEX] [numeric](9, 0) NULL,
	[DOC_SPEC_CD_2] [numeric](2, 0) NULL,
	[DOC_SPEC_CD_3] [numeric](2, 0) NULL,
	[DOC_YTDINC_G] [numeric](9, 0) NULL,
	[DOC_LOCATIONS] [varchar](120) NULL,
	[DOC_RMA_EXPENSE_PERCENT_MISC] [int] NULL,
	[DOC_AFP_PAYM_GROUP] [varchar](4) NULL,
	[DOC_DEPT_2] [numeric](4, 0) NULL,
	[DOC_IND_PAYS_GST] [varchar](1) NULL,
	[DOC_YRLY_CEILING_COMPUTED] [numeric](9, 0) NULL,
	[DOC_YRLY_EXPENSE_COMPUTED] [numeric](9, 0) NULL,
	[DOC_RMA_EXPENSE_PERCENT_REG] [int] NULL,
	[DOC_SUB_SPECIALTY] [varchar](15) NULL,
	[DOC_PAYEFT] [numeric](9, 0) NULL,
	[DOC_YTDDED] [numeric](9, 0) NULL,
	[DOC_DEPT_EXPENSE_PERCENT_MISC] [int] NULL,
	[DOC_DEPT_EXPENSE_PERCENT_REG] [int] NULL,
	[DOC_EP_PED] [numeric](8, 0) NULL,
	[DOC_EP_PAY_CODE] [varchar](1) NULL,
	[DOC_EP_PAY_SUB_CODE] [varchar](1) NULL,
	[DOC_PARTNERSHIP] [varchar](1) NULL,
	[DOC_IND_HOLDBACK_ACTIVE] [varchar](1) NULL,
	[GROUP_REGULAR_SERVICE] [varchar](4) NULL,
	[GROUP_OVER_SERVICED] [varchar](4) NULL,
	[DOC_SPECIALTIES] [varchar](90) NULL,
	[DOC_YRLY_REQUIRE_REVENUE] [numeric](9, 0) NULL,
	[DOC_YRLY_TARGET_REVENUE] [numeric](9, 0) NULL,
	[DOC_CEIREQ] [numeric](9, 0) NULL,
	[DOC_YTDREQ] [numeric](9, 0) NULL,
	[DOC_CEITAR] [numeric](9, 0) NULL,
	[DOC_YTDTAR] [numeric](9, 0) NULL,
	[BILLING_VIA_PAPER_FLAG] [varchar](1) NULL,
	[BILLING_VIA_DISKETTE_FLAG] [varchar](1) NULL,
	[BILLING_VIA_WEB_TEST_FLAG] [varchar](1) NULL,
	[BILLING_VIA_WEB_LIVE_FLAG] [varchar](1) NULL,
	[BILLING_VIA_RMA_DATA_ENTRY] [varchar](1) NULL,
	[DATE_START_RMA_DATA_ENTRY] [numeric](8, 0) NULL,
	[DATE_START_DISKETTE] [numeric](8, 0) NULL,
	[DATE_START_PAPER] [numeric](8, 0) NULL,
	[DATE_START_WEB_LIVE] [numeric](8, 0) NULL,
	[DATE_START_WEB_TEST] [numeric](8, 0) NULL,
	[LEAVE_DESCRIPTION] [varchar](30) NULL,
	[LEAVE_DATE_START] [numeric](8, 0) NULL,
	[LEAVE_DATE_END] [numeric](8, 0) NULL,
	[WEB_USER_REVENUE_ONLY_FLAG] [varchar](1) NULL,
	[MANAGER_FLAG] [varchar](1) NULL,
	[CHAIR_FLAG] [varchar](1) NULL,
	[ABE_USER_FLAG] [varchar](1) NULL,
	[CPSO_NBR] [varchar](6) NULL,
	[CMPA_NBR] [varchar](9) NULL,
	[OMA_NBR] [varchar](10) NULL,
	[CFPC_NBR] [varchar](7) NULL,
	[RCPSC_NBR] [varchar](7) NULL,
	[DOC_MED_PROF_CORP] [varchar](1) NULL,
	[MCMASTER_EMPLOYEE_ID] [numeric](7, 0) NULL,
	[DOC_SPEC_CD_EFF_DATE] [numeric](8, 0) NULL,
	[DOC_SPEC_CD_2_EFF_DATE] [numeric](8, 0) NULL,
	[DOC_SPEC_CD_3_EFF_DATE] [numeric](8, 0) NULL,
	[FACTOR_GST_INCOME_REG] [numeric](5, 0) NULL,
	[FACTOR_GST_INCOME_MISC] [numeric](5, 0) NULL,
	[YELLOW_PAGES_FLAG] [varchar](1) NULL,
	[REPLACED_BY_DOC_NBR] [varchar](3) NULL,
	[PRIOR_DOC_NBR] [varchar](3) NULL,
	[COP_NBR] [varchar](8) NULL,
	[DOC_FLAG_PRIMARY] [varchar](1) NULL,
	[HAS_VALID_CURRENT_PAYROLL_RECORD] [varchar](1) NULL,
	[PAY_THIS_DOCTOR_OHIP_PREMIUM] [varchar](1) NULL,
	[DOC_FISCAL_YR_START_MONTH] [numeric](2, 0) NULL,
	[LAST_MOD_FLAG] [varchar](1) NULL,
	[LAST_MOD_DATE] [numeric](8, 0) NULL,
	[LAST_MOD_TIME] [numeric](4, 0) NULL,
	[LAST_MOD_USER_ID] [varchar](15) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR]
END
CREATE TABLE [SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NOT NULL,
	[DOC_CLINIC_NBR] [numeric](2, 0) NOT NULL,
	[DOC_NX_AVAIL_BATCH] [numeric](3, 0) NULL,
	[DOC_CLINIC_NBR_STATUS] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[DOC_NBR] ASC,
	[DOC_CLINIC_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS]
END
CREATE TABLE [SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NOT NULL,
	[DOC_LOC] [varchar](4) NOT NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[DOC_NBR] ASC,
	[DOC_LOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F053_PAYROLL_UPLOAD]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F053_PAYROLL_UPLOAD]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F053_PAYROLL_UPLOAD]
END
CREATE TABLE [SEQUENTIAL].[F053_PAYROLL_UPLOAD](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLAIM_NBR] [varchar](10) NULL,
	[CLMHDR_BATCH_TYPE] [varchar](1) NULL,
	[PROCESSING_PROGRAM] [varchar](1) NULL,
	[CLMHDR_CURR_PAYMENT] [numeric](7, 0) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F086_PAT_ID]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F086_PAT_ID]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F086_PAT_ID]
END
CREATE TABLE [SEQUENTIAL].[F086_PAT_ID](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_PAT_OHIP_ID_OR_CHART] [varchar](16) NULL,
	[PAT_LAST_BIRTH_DATE] [numeric](8, 0) NULL,
	[PAT_LAST_VERSION_CD] [varchar](2) NULL,
	[PAT_OLD_SURNAME] [varchar](25) NULL,
	[PAT_OLD_GIVEN_NAME] [varchar](17) NULL,
	[PAT_OLD_HEALTH_NBR] [numeric](10, 0) NULL,
	[PAT_OLD_CHART_NBR] [varchar](10) NULL,
	[PAT_OLD_CHART_NBR_2] [varchar](10) NULL,
	[PAT_OLD_CHART_NBR_3] [varchar](10) NULL,
	[PAT_OLD_CHART_NBR_4] [varchar](10) NULL,
	[PAT_OLD_CHART_NBR_5] [varchar](11) NULL,
	[PAT_OLD_ADDR1] [varchar](21) NULL,
	[PAT_OLD_ADDR2] [varchar](21) NULL,
	[PAT_OLD_ADDR3] [varchar](21) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS]
END
CREATE TABLE [SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[ORIG_CLMHDR_PAT_OHIP_ID_OR_CHART] [varchar](16) NULL,
	[ORIG_PAT_OLD_SURNAME] [varchar](15) NULL,
	[ORIG_PAT_OLD_GIVEN_NAME] [varchar](12) NULL,
	[CLMHDR_PAT_OHIP_ID_OR_CHART] [varchar](16) NULL,
	[PAT_OLD_SURNAME] [varchar](15) NULL,
	[PAT_OLD_GIVEN_NAME] [varchar](12) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F110_COMPENSATION_AUDIT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F110_COMPENSATION_AUDIT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F110_COMPENSATION_AUDIT]
END
CREATE TABLE [SEQUENTIAL].[F110_COMPENSATION_AUDIT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NULL,
	[EP_NBR] [numeric](6, 0) NULL,
	[PROCESS_SEQ] [numeric](2, 0) NULL,
	[COMP_CODE] [varchar](6) NULL,
	[COMP_TYPE] [varchar](1) NULL,
	[FACTOR] [numeric](6, 0) NULL,
	[FACTOR_OVERRIDE] [varchar](1) NULL,
	[COMP_UNITS] [numeric](6, 0) NULL,
	[AMT_GROSS] [numeric](9, 0) NULL,
	[AMT_NET] [numeric](9, 0) NULL,
	[EP_NBR_ENTRY] [numeric](6, 0) NULL,
	[COMPENSATION_STATUS] [varchar](1) NULL,
	[LAST_MOD_FLAG] [varchar](1) NULL,
	[LAST_MOD_DATE] [numeric](8, 0) NULL,
	[LAST_MOD_TIME] [numeric](4, 0) NULL,
	[LAST_MOD_USER_ID] [varchar](15) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT]
END
CREATE TABLE [SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NULL,
	[EP_NBR] [numeric](6, 0) NULL,
	[FACTOR] [numeric](6, 0) NULL,
	[DOC_PAY_CODE] [varchar](1) NULL,
	[DOC_PAY_SUB_CODE] [varchar](1) NULL,
	[RETRO_TO_EP_NBR] [numeric](6, 0) NULL,
	[DOC_YRLY_CEILING] [numeric](7, 0) NULL,
	[DOC_YRLY_CEILING_ADJUSTED] [numeric](7, 0) NULL,
	[DOC_YRLY_CEILING_COMPUTED] [numeric](9, 0) NULL,
	[DOC_YRLY_EXPENSE] [numeric](7, 0) NULL,
	[DOC_YRLY_EXPENSE_ADJUSTED] [numeric](7, 0) NULL,
	[DOC_YRLY_EXPENSE_COMPUTED] [numeric](9, 0) NULL,
	[DOC_YRLY_EXPN_ALLOC_PERS] [numeric](2, 0) NULL,
	[DOC_YRLY_CEIL_GUAR] [numeric](9, 0) NULL,
	[DOC_YRLY_CEILING_GUAR_PERC] [numeric](3, 0) NULL,
	[DOC_RMA_EXPENSE_PERCENT_REG] [int] NULL,
	[DOC_RMA_EXPENSE_PERCENT_MISC] [int] NULL,
	[DOC_DEPT_EXPENSE_PERCENT_REG] [int] NULL,
	[DOC_DEPT_EXPENSE_PERCENT_MISC] [int] NULL,
	[DOC_YRLY_REQREV] [int] NULL,
	[DOC_YRLY_REQREV_ADJUSTED] [int] NULL,
	[DOC_YRLY_REQREV_COMPUTED] [numeric](9, 0) NULL,
	[DOC_YRLY_TARREV] [int] NULL,
	[DOC_YRLY_TARREV_ADJUSTED] [int] NULL,
	[DOC_YRLY_TARREV_COMPUTED] [bigint] NULL,
	[RETRO_TO_EP_NBR_REQ] [numeric](6, 0) NULL,
	[RETRO_TO_EP_NBR_TAR] [numeric](6, 0) NULL,
	[LAST_MOD_FLAG] [varchar](1) NULL,
	[LAST_MOD_DATE] [numeric](8, 0) NULL,
	[LAST_MOD_TIME] [numeric](4, 0) NULL,
	[LAST_MOD_USER_ID] [varchar](15) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT]
END
CREATE TABLE [SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NULL,
	[DOC_OHIP_NBR] [numeric](6, 0) NULL,
	[COMP_CODE] [varchar](6) NULL,
	[PROCESS_SEQ] [numeric](2, 0) NULL,
	[COMP_CODE_GROUP] [varchar](1) NULL,
	[REC_TYPE] [varchar](1) NULL,
	[AMT_MTD] [numeric](9, 0) NULL,
	[AMT_YTD] [numeric](9, 0) NULL,
	[LAST_MOD_FLAG] [varchar](1) NULL,
	[LAST_MOD_DATE] [numeric](8, 0) NULL,
	[LAST_MOD_TIME] [numeric](4, 0) NULL,
	[LAST_MOD_USER_ID] [varchar](15) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[ITEM_REC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[ITEM_REC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[ITEM_REC]
END
CREATE TABLE [SEQUENTIAL].[ITEM_REC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[ITEM_TRANS_ID] [varchar](2) NULL,
	[ITEM_REC_ID] [varchar](1) NULL,
	[ITEM_SERVICE_CD] [varchar](5) NULL,
	[ITEM_FILLER_1] [varchar](2) NULL,
	[ITEM_FEE_SUBMIT] [numeric](6, 0) NULL,
	[ITEM_NUM_OF_SERV] [numeric](2, 0) NULL,
	[ITEM_SERVICE_DATE] [numeric](8, 0) NULL,
	[ITEM_DIAG_CD] [varchar](3) NULL,
	[ITEM_FILLER_DIAG] [varchar](1) NULL,
	[ITEM_FILLER_2] [varchar](9) NULL,
	[ITEM_1_OVERRIDE_PRICE] [varchar](1) NULL,
	[ITEM_1_BILATERAL] [varchar](1) NULL,
	[ITEM_2_RESERVED] [varchar](38) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[MEDITECH_PATIENT_FILE_OUT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[MEDITECH_PATIENT_FILE_OUT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[MEDITECH_PATIENT_FILE_OUT]
END
CREATE TABLE [SEQUENTIAL].[MEDITECH_PATIENT_FILE_OUT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[REC_SEQ_NBR] [varchar](6) NULL,
	[REC_LINE] [varchar](204) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[MISC_PAYMENT_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[MISC_PAYMENT_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[MISC_PAYMENT_FILE]
END
CREATE TABLE [SEQUENTIAL].[MISC_PAYMENT_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLINIC_NBR] [numeric](2, 0) NULL,
	[FILLER] [varchar](1) NULL,
	[HDR_AGENT_CD] [varchar](1) NULL,
	[DOC_NBR] [varchar](3) NULL,
	[DOC_NAME] [varchar](24) NULL,
	[CLMDTL_OMA_CD] [varchar](4) NULL,
	[SIGNED_AMT_NET] [numeric](9, 0) NULL,
	[CLMHDR_REFERENCE] [varchar](11) NULL,
	[BYPASS_EDIT] [varchar](6) NULL,
	[FILLER_CR] [varchar](1) NULL,
	[FILLER_LF] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[MOH_OBEC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[MOH_OBEC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[MOH_OBEC]
END
CREATE TABLE [SEQUENTIAL].[MOH_OBEC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[PAT_HEALTH_NBR] [numeric](10, 0) NULL,
	[PAT_VERSION_CD] [varchar](2) NULL,
	[OBEC_SUBMISSION_ID] [varchar](4) NULL,
	[PAT_SEX] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[PARAMETER_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[PARAMETER_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[PARAMETER_FILE]
END
CREATE TABLE [SEQUENTIAL].[PARAMETER_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_PAT_KEY_TYPE] [varchar](1) NULL,
	[CLMHDR_PAT_KEY_DATA] [varchar](15) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[R031A_OHIP_PREMIUMS]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[R031A_OHIP_PREMIUMS]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[R031A_OHIP_PREMIUMS]
END
CREATE TABLE [SEQUENTIAL].[R031A_OHIP_PREMIUMS](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[ICONST_CLINIC_NBR_1_2] [numeric](2, 0) NULL,
	[AFP_GROUP_NAME] [varchar](50) NULL,
	[GROUP_NBR] [varchar](5) NULL,
	[PREMIUM_PAYMENT_DATE] [varchar](10) NULL,
	[DOC_OHIP_NBR] [numeric](6, 0) NULL,
	[DOC_NAME] [varchar](40) NULL,
	[CLMHDR_ADJ_CD] [varchar](5) NULL,
	[PAYMENT_TYPE] [varchar](30) NULL,
	[PAYMENT_PERCENTAGE] [varchar](10) NULL,
	[NBR_OF_CLAIMS] [varchar](10) NULL,
	[DOLLARS_APPROVED] [varchar](10) NULL,
	[DOLLARS_PAID] [varchar](10) NULL,
	[LF] [varchar](1) NULL,
	[CR] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[R070_WORK_MSTR]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[R070_WORK_MSTR]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[R070_WORK_MSTR]
END
CREATE TABLE [SEQUENTIAL].[R070_WORK_MSTR](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_DOC_DEPT] [numeric](2, 0) NULL,
	[FILLER] [varchar](1) NULL,
	[CLMHDR_AGENT_CD] [numeric](1, 0) NULL,
	[CLMHDR_PAT_ACRONYM] [varchar](9) NULL,
	[PAT_OHIP_MMYY] [varchar](15) NULL,
	[CLAIM_NBR] [varchar](10) NULL,
	[CLMHDR_STATUS_OHIP] [varchar](2) NULL,
	[CLMHDR_SUB_NBR] [varchar](1) NULL,
	[DOCREV_MTD_IN_REC] [numeric](8, 0) NULL,
	[DOCREV_MTD_OUT_REC] [numeric](8, 0) NULL,
	[ITEM_FILLER_2] [varchar](8) NULL,
	[ITEM_2_RESERVED] [varchar](8) NULL,
	[CLMHDR_DATE_PERIOD_END] [numeric](8, 0) NULL,
	[CLMHDR_SERV_DATE] [numeric](8, 0) NULL,
	[CLMHDR_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_TAPE_SUBMIT_IND] [varchar](1) NULL,
	[CLMHDR_REFERENCE] [varchar](11) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[RU701_WORK_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[RU701_WORK_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[RU701_WORK_FILE]
END
CREATE TABLE [SEQUENTIAL].[RU701_WORK_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NULL,
	[ICONST_CLINIC_NBR_1_2] [numeric](2, 0) NULL,
	[DOC_SPEC_CD] [numeric](2, 0) NULL,
	[CLMHDR_PAT_ACRONYM] [varchar](9) NULL,
	[CLMHDR_ACCOUNTING_NBR] [varchar](8) NULL,
	[ORIG_REC_NO] [numeric](5, 0) NULL,
	[ACRONYM_FLAG] [varchar](1) NULL,
	[PAGE_AREA] [varchar](1) NULL,
	[PAT_ACRONYM] [varchar](9) NULL,
	[CLMDTL_LINE_NO] [numeric](2, 0) NULL,
	[PRINT_LINE] [varchar](132) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[SUBMIT_DISK_DESC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[SUBMIT_DISK_DESC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[SUBMIT_DISK_DESC]
END
CREATE TABLE [SEQUENTIAL].[SUBMIT_DISK_DESC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMDTL_DOC_OHIP_NBR] [numeric](6, 0) NULL,
	[CLMDTL_ACCOUNTING_NBR] [varchar](8) NULL,
	[CLMDTL_SUSPEND_DESC_255] [varchar](255) NULL,
	[FILLER] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[SUBMIT_DISK_PAT_NEW]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[SUBMIT_DISK_PAT_NEW]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[SUBMIT_DISK_PAT_NEW]
END
CREATE TABLE [SEQUENTIAL].[SUBMIT_DISK_PAT_NEW](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[NEW_PAT_OHIP] [varchar](12) NULL,
	[NEW_PAT_SURNAME] [varchar](25) NULL,
	[NEW_PAT_FIRST_NAME] [varchar](17) NULL,
	[NEW_PAT_SUBSCR_SURNAME] [varchar](25) NULL,
	[NEW_PAT_ADDRESS_LINE_1] [varchar](30) NULL,
	[NEW_PAT_ADDRESS_LINE_2] [varchar](30) NULL,
	[NEW_PAT_ADDRESS_LINE_3] [varchar](30) NULL,
	[NEW_PAT_ADDRESS_PROV_CD] [varchar](2) NULL,
	[NEW_PAT_POSTAL_CODE] [varchar](10) NULL,
	[NEW_PAT_BIRTH_DATE] [varchar](8) NULL,
	[NEW_PAT_SEX] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[SUBMIT_DISK_PAT_OUT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[SUBMIT_DISK_PAT_OUT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[SUBMIT_DISK_PAT_OUT]
END
CREATE TABLE [SEQUENTIAL].[SUBMIT_DISK_PAT_OUT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[SEQ_PAT_DOCTOR_NBR] [numeric](6, 0) NULL,
	[SEQ_PAT_ACCOUNT_NBR] [varchar](8) NULL,
	[SEQ_PAT_I_KEY] [varchar](14) NULL,
	[SEQ_PAT_ACRONYM] [varchar](9) NULL,
	[SEQ_PAT_PROVINCE] [varchar](2) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[TRAILER_REC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[TRAILER_REC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[TRAILER_REC]
END
CREATE TABLE [SEQUENTIAL].[TRAILER_REC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[TRAILER_TRANS_ID] [varchar](2) NULL,
	[TRAILER_REC_ID] [varchar](1) NULL,
	[TRAILER_H_COUNT] [numeric](4, 0) NULL,
	[TRAILER_R_COUNT] [numeric](4, 0) NULL,
	[TRAILER_T_COUNT] [numeric](5, 0) NULL,
	[TRAILER_FILLER] [varchar](63) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[TRANSFER_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[TRANSFER_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[TRANSFER_FILE]
END
CREATE TABLE [SEQUENTIAL].[TRANSFER_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[TRANSFER_BUFFER] [varchar](80) NULL,
	[FILLER] [varchar](1) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U021A_EDT_1HT_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U021A_EDT_1HT_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U021A_EDT_1HT_FILE]
END
CREATE TABLE [SEQUENTIAL].[U021A_EDT_1HT_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[RAT_RMB_MOH_OFF_CD] [varchar](1) NULL,
	[RAT_RMB_GROUP_NBR] [varchar](4) NULL,
	[RAT_RMB_DOC_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_SPECIALTY_CD] [numeric](2, 0) NULL,
	[RAT_RMB_STATION_NBR] [varchar](3) NULL,
	[RAT_RMB_PROCESS_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_HEALTH_NBR] [varchar](10) NULL,
	[RAT_RMB_VERSION_CD] [varchar](2) NULL,
	[RAT_RMB_BIRTH_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_ACCOUNT_NBR] [varchar](8) NULL,
	[RAT_RMB_ORIG_SEQ_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_PAY_PROG] [varchar](3) NULL,
	[RAT_RMB_PAYEE] [varchar](1) NULL,
	[RAT_RMB_REFER_DOC_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_FACILITY_NBR] [varchar](4) NULL,
	[RAT_RMB_ADMIT_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_LOC_CD] [varchar](4) NULL,
	[RAT_RMB_ERROR_H_CD_1] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_2] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_3] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_4] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_5] [varchar](3) NULL,
	[RAT_RMB_SERVICE_CD] [varchar](5) NULL,
	[RAT_RMB_AMOUNT_SUB] [numeric](6, 0) NULL,
	[RAT_RMB_NBR_OF_SERV] [numeric](2, 0) NULL,
	[RAT_RMB_SERVICE_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_DIAG_CD] [varchar](4) NULL,
	[RAT_RMB_T_EXPLAN_CD] [varchar](2) NULL,
	[RAT_RMB_ERROR_T_CD_1] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_2] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_3] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_4] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_5] [varchar](3) NULL,
	[RAT_RMB_8_EXPLAN_CD] [varchar](2) NULL,
	[RAT_RMB_8_EXPLAN_DESC] [varchar](55) NULL,
	[RAT_RMB_FILE_NAME] [varchar](12) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U021A_EDT_RMB_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U021A_EDT_RMB_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U021A_EDT_RMB_FILE]
END
CREATE TABLE [SEQUENTIAL].[U021A_EDT_RMB_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[RAT_RMB_MOH_OFF_CD] [varchar](1) NULL,
	[RAT_RMB_GROUP_NBR] [varchar](4) NULL,
	[RAT_RMB_DOC_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_SPECIALTY_CD] [numeric](2, 0) NULL,
	[RAT_RMB_STATION_NBR] [varchar](3) NULL,
	[RAT_RMB_PROCESS_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_HEALTH_NBR] [varchar](10) NULL,
	[RAT_RMB_VERSION_CD] [varchar](2) NULL,
	[RAT_RMB_BIRTH_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_ACCOUNT_NBR] [varchar](8) NULL,
	[RAT_RMB_ORIG_SEQ_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_PAY_PROG] [varchar](3) NULL,
	[RAT_RMB_PAYEE] [varchar](1) NULL,
	[RAT_RMB_REFER_DOC_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_FACILITY_NBR] [varchar](4) NULL,
	[RAT_RMB_ADMIT_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_LOC_CD] [varchar](4) NULL,
	[RAT_RMB_ERROR_H_CD_1] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_2] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_3] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_4] [varchar](3) NULL,
	[RAT_RMB_ERROR_H_CD_5] [varchar](3) NULL,
	[RAT_RMB_REGISTRATION_NBR] [varchar](12) NULL,
	[RAT_RMB_LAST_NAME] [varchar](9) NULL,
	[RAT_RMB_FIRST_NAME] [varchar](5) NULL,
	[RAT_RMB_SEX] [varchar](1) NULL,
	[RAT_RMB_PROV_CD] [varchar](2) NULL,
	[RAT_RMB_ERROR_R_CD_1] [varchar](3) NULL,
	[RAT_RMB_ERROR_R_CD_2] [varchar](3) NULL,
	[RAT_RMB_ERROR_R_CD_3] [varchar](3) NULL,
	[RAT_RMB_ERROR_R_CD_4] [varchar](3) NULL,
	[RAT_RMB_ERROR_R_CD_5] [varchar](3) NULL,
	[RAT_RMB_SERVICE_CD] [varchar](5) NULL,
	[RAT_RMB_AMOUNT_SUB] [numeric](6, 0) NULL,
	[RAT_RMB_NBR_OF_SERV] [numeric](2, 0) NULL,
	[RAT_RMB_SERVICE_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_DIAG_CD] [varchar](4) NULL,
	[RAT_RMB_T_EXPLAN_CD] [varchar](2) NULL,
	[RAT_RMB_ERROR_T_CD_1] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_2] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_3] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_4] [varchar](3) NULL,
	[RAT_RMB_ERROR_T_CD_5] [varchar](3) NULL,
	[RAT_RMB_8_EXPLAN_CD] [varchar](2) NULL,
	[RAT_RMB_8_EXPLAN_DESC] [varchar](55) NULL,
	[RAT_RMB_FILE_NAME] [varchar](12) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U030_TAPE_145_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_145_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U030_TAPE_145_FILE]
END
CREATE TABLE [SEQUENTIAL].[U030_TAPE_145_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[RAT_145_GROUP_NBR] [varchar](4) NULL,
	[RAT_145_MOH_OFF_CD] [varchar](1) NULL,
	[RAT_145_DATA_SEQ_NBR] [numeric](1, 0) NULL,
	[RAT_145_PAYMENT_DATE] [numeric](8, 0) NULL,
	[RAT_145_PAY_LAST_NAME] [varchar](25) NULL,
	[RAT_145_PAY_TITLE] [varchar](3) NULL,
	[RAT_145_PAY_INITIALS] [varchar](2) NULL,
	[RAT_145_TOT_AMT_PAY] [numeric](9, 0) NULL,
	[RAT_145_CHEQ_NBR] [varchar](8) NULL,
	[RAT_145_CLAIM_NBR] [varchar](11) NULL,
	[RAT_145_TRANS_TYPE] [numeric](1, 0) NULL,
	[RAT_145_DOC_NBR] [numeric](6, 0) NULL,
	[RAT_145_SPECIALTY_CD] [numeric](2, 0) NULL,
	[RAT_145_ACCOUNT_NBR] [varchar](8) NULL,
	[RAT_145_LAST_NAME] [varchar](14) NULL,
	[RAT_145_FIRST_NAME] [varchar](5) NULL,
	[RAT_145_PROV_CD] [varchar](2) NULL,
	[RAT_145_HEALTH_OHIP_NBR] [varchar](12) NULL,
	[RAT_145_VERSION_CD] [varchar](2) NULL,
	[RAT_145_PAY_PROG] [varchar](3) NULL,
	[RAT_145_CONV_HEALTH_NBR] [varchar](10) NULL,
	[RAT_145_SERVICE_DATE] [numeric](8, 0) NULL,
	[RAT_145_NBR_OF_SERV] [numeric](2, 0) NULL,
	[RAT_145_SERVICE_CD] [varchar](5) NULL,
	[RAT_145_ELIGIBILITY_IND] [varchar](1) NULL,
	[RAT_145_AMOUNT_SUB] [numeric](6, 0) NULL,
	[RAT_145_AMT_PAID] [numeric](6, 0) NULL,
	[RAT_145_EXPLAN_CD] [varchar](2) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U030_TAPE_67_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_67_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U030_TAPE_67_FILE]
END
CREATE TABLE [SEQUENTIAL].[U030_TAPE_67_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[RAT_67_AMT_CLAIMS_ADJ] [numeric](9, 0) NULL,
	[RAT_67_AMT_ADVANCES] [numeric](9, 0) NULL,
	[RAT_67_AMT_REDUCTIONS] [numeric](9, 0) NULL,
	[RAT_67_AMT_DEDUCTIONS] [numeric](9, 0) NULL,
	[RAT_67_TRANS_CD] [varchar](2) NULL,
	[RAT_67_CHEQUE_IND] [varchar](1) NULL,
	[RAT_67_TRANS_DATE] [numeric](8, 0) NULL,
	[RAT_67_TRANS_AMT] [numeric](8, 0) NULL,
	[RAT_67_TRANS_MESSAGE] [varchar](50) NULL,
	[RAT_67_TOTAL_CLINIC_AMT] [numeric](9, 0) NULL,
	[RAT_67_AMT_BILL] [numeric](9, 0) NULL,
	[RAT_67_AMT_PAID] [numeric](9, 0) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U030_TAPE_8_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_8_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U030_TAPE_8_FILE]
END
CREATE TABLE [SEQUENTIAL].[U030_TAPE_8_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[RAT_8_MESSAGE_TEXT] [varchar](70) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U030_TAPE_RMB_FILE]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_RMB_FILE]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U030_TAPE_RMB_FILE]
END
CREATE TABLE [SEQUENTIAL].[U030_TAPE_RMB_FILE](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[RAT_RMB_GROUP_NBR] [varchar](4) NULL,
	[RAT_RMB_MOH_OFF_CD] [varchar](1) NULL,
	[RAT_RMB_DATA_SEQ_NBR] [numeric](1, 0) NULL,
	[RAT_RMB_PAYMENT_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_PAY_LAST_NAME] [varchar](25) NULL,
	[RAT_RMB_PAY_TITLE] [varchar](3) NULL,
	[RAT_RMB_PAY_INITIALS] [varchar](2) NULL,
	[RAT_RMB_TOT_AMT_PAY] [numeric](9, 0) NULL,
	[RAT_RMB_CHEQ_NBR] [varchar](8) NULL,
	[RAT_RMB_CLAIM_NBR] [varchar](11) NULL,
	[RAT_RMB_TRANS_TYPE] [numeric](1, 0) NULL,
	[RAT_RMB_DOC_NBR] [numeric](6, 0) NULL,
	[RAT_RMB_SPECIALTY_CD] [numeric](2, 0) NULL,
	[RAT_RMB_ACCOUNT_NBR] [varchar](8) NULL,
	[RAT_RMB_LAST_NAME] [varchar](14) NULL,
	[RAT_RMB_FIRST_NAME] [varchar](5) NULL,
	[RAT_RMB_PROV_CD] [varchar](2) NULL,
	[RAT_RMB_HEALTH_OHIP_NBR] [varchar](12) NULL,
	[RAT_RMB_VERSION_CD] [varchar](2) NULL,
	[RAT_RMB_PAY_PROG] [varchar](3) NULL,
	[RAT_RMB_CONV_HEALTH_NBR] [varchar](10) NULL,
	[RAT_RMB_SERVICE_DATE] [numeric](8, 0) NULL,
	[RAT_RMB_NBR_OF_SERV] [numeric](2, 0) NULL,
	[RAT_RMB_SERVICE_CD] [varchar](5) NULL,
	[RAT_RMB_ELIGIBILITY_IND] [varchar](1) NULL,
	[RAT_RMB_AMOUNT_SUB] [numeric](6, 0) NULL,
	[RAT_RMB_AMT_PAID] [numeric](6, 0) NULL,
	[RAT_RMB_EXPLAN_CD] [varchar](2) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[U132DAT]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U132DAT]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[U132DAT]
END
CREATE TABLE [SEQUENTIAL].[U132DAT](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[DOC_NBR] [varchar](3) NULL,
	[FILLER] [varchar](1) NULL,
	[DOC_NAME] [varchar](24) NULL,
	[DOC_INITS] [varchar](3) NULL,
	[DOC_GIVEN_NAMES] [varchar](24) NULL,
	[SIGNED_AMT_NET] [numeric](9, 0) NULL,
	[COMP_CODE] [varchar](6) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Table [SEQUENTIAL].[WEB_HEH_REC]    Script Date: 5/25/2017 5:17:13 PM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[WEB_HEH_REC]') AND type in (N'U'))
BEGIN
DROP TABLE [SEQUENTIAL].[WEB_HEH_REC]
END
CREATE TABLE [SEQUENTIAL].[WEB_HEH_REC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_1_TRANS_ID] [varchar](2) NULL,
	[CLMHDR_1_REC_ID] [varchar](1) NULL,
	[CLMHDR_1_HEALTH_NUM] [varchar](10) NULL,
	[CLMHDR_1_VERSION_CD] [varchar](2) NULL,
	[CLMHDR_1_BIRTH_DATE] [numeric](8, 0) NULL,
	[CLMHDR_1_ACCOUNT_NUM] [varchar](8) NULL,
	[CLMHDR_1_PAYMENT_PRG] [varchar](3) NULL,
	[CLMHDR_1_PAYEE] [varchar](1) NULL,
	[CLMHDR_1_REF_DOC_NUM] [numeric](6, 0) NULL,
	[CLMHDR_1_HOSP_NUM] [numeric](4, 0) NULL,
	[CLMHDR_1_ADMIT_DATE] [numeric](8, 0) NULL,
	[CLMHDR_1_REF_LAB_NUM] [numeric](4, 0) NULL,
	[CLMHDR_1_MAN_REV_IND] [varchar](1) NULL,
	[CLMHDR_1_LOC_CODE] [varchar](4) NULL,
	[CLMHDR_1_FILLER] [varchar](18) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

SET ANSI_PADDING OFF

/****** Object:  Trigger [SEQUENTIAL].[ADJ_CLAIM_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[ADJ_CLAIM_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[ADJ_CLAIM_FILE_CHECK] ON [SEQUENTIAL].[ADJ_CLAIM_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''ADJ_CLAIM_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE ADJ_CLAIM_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[AFP_A1F_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A1F_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[AFP_A1F_FILE_CHECK] ON [SEQUENTIAL].[AFP_A1F_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''AFP_A1F_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE AFP_A1F_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[AFP_A2G_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A2G_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[AFP_A2G_FILE_CHECK] ON [SEQUENTIAL].[AFP_A2G_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''AFP_A2G_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE AFP_A2G_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[AFP_A2S_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A2S_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[AFP_A2S_FILE_CHECK] ON [SEQUENTIAL].[AFP_A2S_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''AFP_A2S_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE AFP_A2S_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[AFP_A3C_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A3C_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[AFP_A3C_FILE_CHECK] ON [SEQUENTIAL].[AFP_A3C_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''AFP_A3C_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE AFP_A3C_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[AFP_A4T_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[AFP_A4T_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[AFP_A4T_FILE_CHECK] ON [SEQUENTIAL].[AFP_A4T_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''AFP_A4T_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE AFP_A4T_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[BATHDR_REC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[BATHDR_REC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[BATHDR_REC_CHECK] ON [SEQUENTIAL].[BATHDR_REC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''BATHDR_REC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE BATHDR_REC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE_CHECK] ON [SEQUENTIAL].[CLAIMS_HISTORY_SUBFILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''CLAIMS_HISTORY_SUBFILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE CLAIMS_HISTORY_SUBFILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[CLAIMS_WORK_MSTR_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLAIMS_WORK_MSTR_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[CLAIMS_WORK_MSTR_CHECK] ON [SEQUENTIAL].[CLAIMS_WORK_MSTR] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''CLAIMS_WORK_MSTR'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE CLAIMS_WORK_MSTR SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[CLMHDR_1_REC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLMHDR_1_REC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[CLMHDR_1_REC_CHECK] ON [SEQUENTIAL].[CLMHDR_1_REC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''CLMHDR_1_REC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE CLMHDR_1_REC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[CLMHDR_2_REC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[CLMHDR_2_REC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[CLMHDR_2_REC_CHECK] ON [SEQUENTIAL].[CLMHDR_2_REC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''CLMHDR_2_REC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE CLMHDR_2_REC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F002_DTL_AFTER_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F002_DTL_AFTER_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F002_DTL_AFTER_CHECK] ON [SEQUENTIAL].[F002_DTL_AFTER] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F002_DTL_AFTER'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F002_DTL_AFTER SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F002_DTL_BEFORE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F002_DTL_BEFORE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F002_DTL_BEFORE_CHECK] ON [SEQUENTIAL].[F002_DTL_BEFORE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F002_DTL_BEFORE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F002_DTL_BEFORE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F020_DOCTOR_AUDIT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F020_DOCTOR_AUDIT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F020_DOCTOR_AUDIT_CHECK] ON [SEQUENTIAL].[F020_DOCTOR_AUDIT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F020_DOCTOR_AUDIT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F020_DOCTOR_AUDIT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR_CHECK] ON [SEQUENTIAL].[F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F020C_DOCTOR_AUDIT_NEXT_BATCH_NBR SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS_CHECK] ON [SEQUENTIAL].[F020L_DOCTOR_AUDIT_LOCATIONS] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F020L_DOCTOR_AUDIT_LOCATIONS'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F020L_DOCTOR_AUDIT_LOCATIONS SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F053_PAYROLL_UPLOAD_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F053_PAYROLL_UPLOAD_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F053_PAYROLL_UPLOAD_CHECK] ON [SEQUENTIAL].[F053_PAYROLL_UPLOAD] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F053_PAYROLL_UPLOAD'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F053_PAYROLL_UPLOAD SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F086_PAT_ID_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F086_PAT_ID_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F086_PAT_ID_CHECK] ON [SEQUENTIAL].[F086_PAT_ID] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F086_PAT_ID'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F086_PAT_ID SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS_CHECK] ON [SEQUENTIAL].[F086A_ORIG_NEW_PAT_IDS] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F086A_ORIG_NEW_PAT_IDS'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F086A_ORIG_NEW_PAT_IDS SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F110_COMPENSATION_AUDIT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F110_COMPENSATION_AUDIT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F110_COMPENSATION_AUDIT_CHECK] ON [SEQUENTIAL].[F110_COMPENSATION_AUDIT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F110_COMPENSATION_AUDIT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F110_COMPENSATION_AUDIT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT_CHECK] ON [SEQUENTIAL].[F112_PYCDCEILINGS_AUDIT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F112_PYCDCEILINGS_AUDIT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F112_PYCDCEILINGS_AUDIT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT_CHECK] ON [SEQUENTIAL].[F119_DOCTOR_YTD_AUDIT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''F119_DOCTOR_YTD_AUDIT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE F119_DOCTOR_YTD_AUDIT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[ITEM_REC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[ITEM_REC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[ITEM_REC_CHECK] ON [SEQUENTIAL].[ITEM_REC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''ITEM_REC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE ITEM_REC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[MEDITECHPATIENTFILEOUT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[MEDITECHPATIENTFILEOUT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[MEDITECHPATIENTFILEOUT_CHECK] ON [SEQUENTIAL].[MEDITECH_PATIENT_FILE_OUT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''MEDITECH_PATIENT_FILE_OUT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE MEDITECH_PATIENT_FILE_OUT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[MISC_PAYMENT_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[MISC_PAYMENT_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[MISC_PAYMENT_FILE_CHECK] ON [SEQUENTIAL].[MISC_PAYMENT_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''MISC_PAYMENT_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE MISC_PAYMENT_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[MOH_OBEC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[MOH_OBEC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[MOH_OBEC_CHECK] ON [SEQUENTIAL].[MOH_OBEC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''MOH_OBEC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE MOH_OBEC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[PARAMETER_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[PARAMETER_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[PARAMETER_FILE_CHECK] ON [SEQUENTIAL].[PARAMETER_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''PARAMETER_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE PARAMETER_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[R031A_OHIP_PREMIUMS_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[R031A_OHIP_PREMIUMS_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[R031A_OHIP_PREMIUMS_CHECK] ON [SEQUENTIAL].[R031A_OHIP_PREMIUMS] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''R031A_OHIP_PREMIUMS'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE R031A_OHIP_PREMIUMS SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[R070_WORK_MSTR_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[R070_WORK_MSTR_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[R070_WORK_MSTR_CHECK] ON [SEQUENTIAL].[R070_WORK_MSTR] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''R070_WORK_MSTR'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE R070_WORK_MSTR SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[RU701_WORK_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[RU701_WORK_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[RU701_WORK_FILE_CHECK] ON [SEQUENTIAL].[RU701_WORK_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''RU701_WORK_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE RU701_WORK_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[SUBMIT_DISK_DESC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[SUBMIT_DISK_DESC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[SUBMIT_DISK_DESC_CHECK] ON [SEQUENTIAL].[SUBMIT_DISK_DESC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''SUBMIT_DISK_DESC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE SUBMIT_DISK_DESC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[SUBMIT_DISK_PAT_NEW_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[SUBMIT_DISK_PAT_NEW_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[SUBMIT_DISK_PAT_NEW_CHECK] ON [SEQUENTIAL].[SUBMIT_DISK_PAT_NEW] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''SUBMIT_DISK_PAT_NEW'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE SUBMIT_DISK_PAT_NEW SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[SUBMIT_DISK_PAT_OUT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[SUBMIT_DISK_PAT_OUT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[SUBMIT_DISK_PAT_OUT_CHECK] ON [SEQUENTIAL].[SUBMIT_DISK_PAT_OUT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''SUBMIT_DISK_PAT_OUT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE SUBMIT_DISK_PAT_OUT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[TRAILER_REC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[TRAILER_REC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[TRAILER_REC_CHECK] ON [SEQUENTIAL].[TRAILER_REC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''TRAILER_REC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE TRAILER_REC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[TRANSFER_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[TRANSFER_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[TRANSFER_FILE_CHECK] ON [SEQUENTIAL].[TRANSFER_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''TRANSFER_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE TRANSFER_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U021A_EDT_1HT_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U021A_EDT_1HT_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U021A_EDT_1HT_FILE_CHECK] ON [SEQUENTIAL].[U021A_EDT_1HT_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U021A_EDT_1HT_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U021A_EDT_1HT_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U021A_EDT_RMB_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U021A_EDT_RMB_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U021A_EDT_RMB_FILE_CHECK] ON [SEQUENTIAL].[U021A_EDT_RMB_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U021A_EDT_RMB_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U021A_EDT_RMB_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U030_TAPE_145_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_145_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U030_TAPE_145_FILE_CHECK] ON [SEQUENTIAL].[U030_TAPE_145_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U030_TAPE_145_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U030_TAPE_145_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U030_TAPE_67_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_67_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U030_TAPE_67_FILE_CHECK] ON [SEQUENTIAL].[U030_TAPE_67_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U030_TAPE_67_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U030_TAPE_67_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U030_TAPE_8_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_8_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U030_TAPE_8_FILE_CHECK] ON [SEQUENTIAL].[U030_TAPE_8_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U030_TAPE_8_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U030_TAPE_8_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U030_TAPE_RMB_FILE_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U030_TAPE_RMB_FILE_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U030_TAPE_RMB_FILE_CHECK] ON [SEQUENTIAL].[U030_TAPE_RMB_FILE] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U030_TAPE_RMB_FILE'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U030_TAPE_RMB_FILE SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[U132DAT_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[U132DAT_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[U132DAT_CHECK] ON [SEQUENTIAL].[U132DAT] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''U132DAT'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE U132DAT SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'

/****** Object:  Trigger [SEQUENTIAL].[WEB_HEH_REC_CHECK]    Script Date: 5/25/2017 5:17:13 PM ******/
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[SEQUENTIAL].[WEB_HEH_REC_CHECK]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER [SEQUENTIAL].[WEB_HEH_REC_CHECK] ON [SEQUENTIAL].[WEB_HEH_REC] FOR INSERT, UPDATE AS 
DECLARE @old INTEGER, @new INTEGER, @rowid uniqueidentifier
SELECT @old = CHECKSUM_VALUE FROM deleted
SELECT @new = CHECKSUM_VALUE FROM inserted
IF @old <> @new
BEGIN
   RAISERROR(50501, 16, 1, ''WEB_HEH_REC'')
   ROLLBACK TRANSACTION
END
ELSE
BEGIN
   INSERT INTO SEQUENTIAL.CHECKSUM_IDS(ID) VALUES(1);
   UPDATE WEB_HEH_REC SET CHECKSUM_VALUE=@@IDENTITY WHERE ROWID IN (SELECT ROWID FROM INSERTED);
END
'
