
01  TAPEOUT-TRAILER-REC.

    05  TAPEOUT-TRAILER-CLMHDR-CNT		PIC 9(4).
    05  TAPEOUT-TRAILER-ITM-CNT			PIC 9(5).
    05  TAPEOUT-TRAILER-PAT-ADDR-CNT		PIC 9(4).
    05  TAPEOUT-TRAILER-BAT-CNT			PIC 9(3).
    05  FILLER					PIC X(133).
    05  TAPEOUT-TRAILER-VALUE-E			PIC X.
