
01  TAPEOUT-PAT-ADDR-REC.

    05  TAPEOUT-PAT-ADDR-VALUE-HEA		PIC X(3).
    05  TAPEOUT-PAT-ADDR-1			PIC X(25).
    05  TAPEOUT-PAT-ADDR-2			PIC X(25).
    05  TAPEOUT-PAT-ADDR-3			PIC X(18).
    05  TAPEOUT-PAT-ADDR-POST-CD.
	10  TAPEOUT-PAT-ADDR-POST-CD1		PIC X.
	10  TAPEOUT-PAT-ADDR-POST-CD2		PIC 9.
	10  TAPEOUT-PAT-ADDR-POST-CD3		PIC X.
	10  TAPEOUT-PAT-ADDR-POST-CD4		PIC 9.
	10  TAPEOUT-PAT-ADDR-POST-CD5		PIC X.
	10  TAPEOUT-PAT-ADDR-POST-CD6		PIC 9.
    05  FILLER					PIC X(2).
