USE [%DatabaseName%]

IF  NOT EXISTS (SELECT * FROM INDEXED.RENAISSANCE_SECURITY WHERE User_Name = 'SA')INSERT INTO INDEXED.Renaissance_Security (USER_NAME,PSWD,SECURITY_CLASS,PSWD_EXPIRY_DATE,PSWD_DURATION,EMAIL_ADDRESS) VALUES('SA', 'xi{{gzl','PROXY','',0,'')
INSERT INTO INDEXED.RENAISSANCE_SECURITY (USER_NAME,PSWD,SECURITY_CLASS,PSWD_EXPIRY_DATE, PSWD_DURATION,EMAIL_ADDRESS,Not_Chg_Before,Acc_Attempts,Acc_Lck_Out) VALUES('USER','xi{{gzl','SA', '1/1/1900 12:00:00 AM',0,'', '1/1/1900 12:00:00 AM',0,null)
INSERT INTO INDEXED.RENAISSANCE_USER_ROLES (USER_NAME,ROLE_NAME,ROLE_PRIORITY) VALUES('USER','SA',1)

