USE [%DatabaseName%]

/****** Object:  Table [WEB11].[F002_SUSPEND_ADDRESS]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[WEB11].[F002_SUSPEND_ADDRESS]') AND type in (N'U'))
BEGIN
DROP TABLE [WEB11].[F002_SUSPEND_ADDRESS]
END
CREATE TABLE [WEB11].[F002_SUSPEND_ADDRESS](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[ADD_ADDRESS_LINE_1] [varchar](25) NULL,
	[ADD_ADDRESS_LINE_2] [varchar](25) NULL,
	[ADD_ADDRESS_LINE_3] [varchar](25) NULL,
	[ADD_POSTAL_CODE] [varchar](9) NULL,
	[ADD_SURNAME] [varchar](25) NULL,
	[ADD_FIRST_NAME] [varchar](25) NULL,
	[ADD_BIRTH_DATE] [numeric](8, 0) NULL,
	[ADD_SEX] [varchar](1) NULL,
	[ADD_PHONE_NO] [varchar](20) NULL,
	[ADD_DOC_OHIP_NBR] [numeric](6, 0) NOT NULL,
	[ADD_ACCOUNTING_NBR] [varchar](8) NOT NULL,
	[DEBUG_INFO][varchar](3000) NULL,
	[ERROR_FLAG][numeric](1,0) NULL,
	[INPUT_FILE_LOCATION][varchar](256) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[ADD_DOC_OHIP_NBR] ASC,
	[ADD_ACCOUNTING_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_ADDRESS_SUSPEND_ADD_ID] ON [WEB11].[F002_SUSPEND_ADDRESS]
(
	[ADD_DOC_OHIP_NBR] ASC,
	[ADD_ACCOUNTING_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_ADDRESS_ROWID] ON [WEB11].[F002_SUSPEND_ADDRESS]
(
	[ROWID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

SET ANSI_PADDING OFF

/****** Object:  Table [WEB11].[F002_SUSPEND_DESC]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[WEB11].[F002_SUSPEND_DESC]') AND type in (N'U'))
BEGIN
DROP TABLE [WEB11].[F002_SUSPEND_DESC]
END
CREATE TABLE [WEB11].[F002_SUSPEND_DESC](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMDTL_SUSPEND_DESC] [varchar](70) NULL,
	[CLMDTL_STATUS] [varchar](1) NULL,
	[CLMDTL_DOC_OHIP_NBR] [numeric](6, 0) NOT NULL,
	[CLMDTL_ACCOUNTING_NBR] [varchar](8) NOT NULL,
	[CLMDTL_LINE_NO] [numeric](2, 0) NOT NULL,
	[DEBUG_INFO][varchar](3000) NULL,
	[ERROR_FLAG][numeric](1,0) NULL,
	[INPUT_FILE_LOCATION][varchar](256) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[CLMDTL_DOC_OHIP_NBR] ASC,
	[CLMDTL_ACCOUNTING_NBR] ASC,
	[CLMDTL_LINE_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_DESC_SUSPEND_DTL_ID] ON [WEB11].[F002_SUSPEND_DESC]
(
	[CLMDTL_DOC_OHIP_NBR] ASC,
	[CLMDTL_ACCOUNTING_NBR] ASC,
	[CLMDTL_LINE_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_DESC_ROWID] ON [WEB11].[F002_SUSPEND_DESC]
(
	[ROWID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

SET ANSI_PADDING OFF

/****** Object:  Table [WEB11].[F002_SUSPEND_DTL]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[WEB11].[F002_SUSPEND_DTL]') AND type in (N'U'))
BEGIN
DROP TABLE [WEB11].[F002_SUSPEND_DTL]
END
CREATE TABLE [WEB11].[F002_SUSPEND_DTL](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMDTL_BATCH_NBR] [varchar](8) NULL,
	[CLMDTL_CLAIM_NBR] [numeric](2, 0) NULL,
	[CLMDTL_OMA_CD] [varchar](4) NULL,
	[CLMDTL_OMA_SUFF] [varchar](1) NULL,
	[CLMDTL_ADJ_NBR] [numeric](1, 0) NULL,
	[CLMDTL_REV_GROUP_CD] [varchar](3) NULL,
	[CLMDTL_AGENT_CD] [numeric](1, 0) NULL,
	[CLMDTL_ADJ_CD] [varchar](1) NULL,
	[CLMDTL_NBR_SERV] [numeric](2, 0) NULL,
	[CLMDTL_SV_YY] [numeric](4, 0) NULL,
	[CLMDTL_SV_MM] [numeric](2, 0) NULL,
	[CLMDTL_SV_DD] [numeric](2, 0) NULL,
	[CLMDTL_CONSEC_DATES_R] [varchar](9) NULL,
	[CLMDTL_AMT_TECH_BILLED] [numeric](6, 0) NULL,
	[CLMDTL_FEE_OMA] [numeric](7, 0) NULL,
	[CLMDTL_FEE_OHIP] [numeric](7, 0) NULL,
	[CLMDTL_DATE_PERIOD_END] [varchar](8) NULL,
	[CLMDTL_CYCLE_NBR] [numeric](3, 0) NULL,
	[CLMDTL_DIAG_CD] [numeric](3, 0) NULL,
	[CLMDTL_DIAG_CD_LOCAL] [numeric](3, 0) NULL,
	[CLMDTL_STATUS] [varchar](1) NULL,
	[CLMDTL_DOC_OHIP_NBR] [numeric](6, 0) NULL,
	[CLMDTL_ACCOUNTING_NBR] [varchar](8) NULL,
	[DEBUG_INFO][varchar](3000) NULL,
	[ERROR_FLAG][numeric](1,0) NULL,
	[INPUT_FILE_LOCATION][varchar](256) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [F002_SUSPEND_DTL_SUSPEND_DTL_ID] ON [WEB11].[F002_SUSPEND_DTL]
(
	[CLMDTL_DOC_OHIP_NBR] ASC,
	[CLMDTL_ACCOUNTING_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_DTL_ROWID] ON [WEB11].[F002_SUSPEND_DTL]
(
	[ROWID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

SET ANSI_PADDING OFF

/****** Object:  Table [WEB11].[F002_SUSPEND_HDR]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[WEB11].[F002_SUSPEND_HDR]') AND type in (N'U'))
BEGIN
DROP TABLE [WEB11].[F002_SUSPEND_HDR]
END
CREATE TABLE [WEB11].[F002_SUSPEND_HDR](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_CLINIC_NBR_1_2] [numeric](2, 0) NULL,
	[CLMHDR_DOC_NBR] [varchar](3) NULL,
	[CLMHDR_WEEK] [numeric](2, 0) NULL,
	[CLMHDR_DAY] [numeric](1, 0) NULL,
	[CLMHDR_CLAIM_NBR] [numeric](2, 0) NULL,
	[CLMHDR_ADJ_OMA_CD] [varchar](4) NULL,
	[CLMHDR_ADJ_OMA_SUFF] [varchar](1) NULL,
	[CLMHDR_ADJ_ADJ_NBRF] [varchar](1) NULL,
	[CLMHDR_BATCH_TYPE] [varchar](1) NULL,
	[CLMHDR_ADJ_CD_SUB_TYPE] [varchar](1) NULL,
	[CLMHDR_DOC_NBR_OHIP] [numeric](6, 0) NULL,
	[CLMHDR_DOC_SPEC_CD] [numeric](2, 0) NULL,
	[CLMHDR_REFER_DOC_NBR] [numeric](6, 0) NULL,
	[CLMHDR_DIAG_CD] [numeric](3, 0) NULL,
	[CLMHDR_LOC] [varchar](4) NULL,
	[CLMHDR_HOSP] [varchar](1) NULL,
	[CLMHDR_AGENT_CD] [numeric](1, 0) NULL,
	[CLMHDR_ADJ_CD] [varchar](1) NULL,
	[CLMHDR_TAPE_SUBMIT_IND] [varchar](1) NULL,
	[CLMHDR_I_O_PAT_IND] [varchar](1) NULL,
	[CLMHDR_PAT_KEY_TYPE] [varchar](1) NULL,
	[CLMHDR_PAT_KEY_DATA] [varchar](15) NULL,
	[CLMHDR_PAT_ACRONYM6] [varchar](6) NULL,
	[CLMHDR_PAT_ACRONYM3] [varchar](3) NULL,
	[CLMHDR_REFERENCE] [varchar](11) NULL,
	[CLMHDR_DATE_ADMIT] [varchar](8) NULL,
	[CLMHDR_DOC_DEPT] [numeric](2, 0) NULL,
	[CLMHDR_DATE_CASH_TAPE_PAYMENT] [varchar](8) NULL,
	[CLMHDR_MSG_NBR] [varchar](2) NULL,
	[CLMHDR_REPRINT_FLAG] [varchar](1) NULL,
	[CLMHDR_SUB_NBR] [varchar](1) NULL,
	[CLMHDR_AUTO_LOGOUT] [varchar](1) NULL,
	[CLMHDR_FEE_COMPLEX] [varchar](1) NULL,
	[FILLER] [varchar](2) NULL,
	[CLMHDR_CURR_PAYMENT] [numeric](7, 0) NULL,
	[CLMHDR_DATE_PERIOD_END] [numeric](8, 0) NULL,
	[CLMHDR_CYCLE_NBR] [numeric](2, 0) NULL,
	[CLMHDR_DATE_SYS] [varchar](8) NULL,
	[CLMHDR_AMT_TECH_BILLED] [numeric](6, 0) NULL,
	[CLMHDR_AMT_TECH_PAID] [numeric](6, 0) NULL,
	[CLMHDR_TOT_CLAIM_AR_OMA] [numeric](7, 0) NULL,
	[CLMHDR_TOT_CLAIM_AR_OHIP] [numeric](7, 0) NULL,
	[CLMHDR_MANUAL_AND_TAPE_PAYMENTS] [numeric](7, 0) NULL,
	[CLMHDR_STATUS_OHIP] [varchar](2) NULL,
	[CLMHDR_ORIG_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_ORIG_CLAIM_NBR] [numeric](2, 0) NULL,
	[CLMHDR_STATUS] [varchar](1) NULL,
	[CLMHDR_HEALTH_CARE_NBR] [varchar](12) NULL,
	[CLMHDR_HEALTH_CARE_VER] [varchar](2) NULL,
	[CLMHDR_HEALTH_CARE_PROV] [varchar](2) NULL,
	[CLMHDR_RELATIONSHIP] [varchar](1) NULL,
	[CLMHDR_PATIENT_SURNAME] [varchar](25) NULL,
	[CLMHDR_SUBSCR_INITIALS] [varchar](3) NULL,
	[CLMHDR_WCB_CLAIM_NBR] [varchar](9) NULL,
	[CLMHDR_WCB_ACCIDENT_DATE] [numeric](8, 0) NULL,
	[CLMHDR_WCB_EMPLOYER_NAME_ADDR] [varchar](40) NULL,
	[CLMHDR_WCB_EMPLOYER_POSTAL_CODE] [varchar](6) NULL,
	[CLMHDR_CONFIDENTIAL_FLAG] [varchar](1) NULL,
	[CLMHDR_NBR_SUSPEND_DESC_RECS] [numeric](2, 0) NULL,
	[FILLER2] [varchar](1) NULL,
	[CLMHDR_DOC_OHIP_NBR] [numeric](6, 0) NOT NULL,
	[CLMHDR_ACCOUNTING_NBR] [varchar](8) NOT NULL,
	[SUSP_HDR_DOC_NBR] [varchar](3) NULL,
	[SUSP_HDR_CLINIC_NBR] [numeric](2, 0) NULL,
	[SUSP_HDR_ACRONYM] [varchar](9) NULL,
	[SUSP_HDR_ACCOUNTING_NBR] [varchar](8) NULL,
	[DEBUG_INFO][varchar](3000) NULL,
	[ERROR_FLAG][numeric](1,0) NULL,
	[INPUT_FILE_LOCATION][varchar](256) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[CLMHDR_DOC_OHIP_NBR] ASC,
	[CLMHDR_ACCOUNTING_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_HDR_SUSPEND_HDR_ACR] ON [WEB11].[F002_SUSPEND_HDR]
(
	[SUSP_HDR_DOC_NBR] ASC,
	[SUSP_HDR_CLINIC_NBR] ASC,
	[SUSP_HDR_ACRONYM] ASC,
	[SUSP_HDR_ACCOUNTING_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_HDR_SUSPEND_HDR_ID] ON [WEB11].[F002_SUSPEND_HDR]
(
	[CLMHDR_DOC_OHIP_NBR] ASC,
	[CLMHDR_ACCOUNTING_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [F002_SUSPEND_HDR_ROWID] ON [WEB11].[F002_SUSPEND_HDR]
(
	[ROWID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

SET ANSI_PADDING OFF
