

/****** Object:  Table [INDEXED].[F002_CLAIMS_MSTR]    Script Date: 5/25/2017 11:55:55 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[INDEXED].[F002_CLAIMS_MSTR]') AND type in (N'U'))
BEGIN
CREATE TABLE [INDEXED].[F002_CLAIMS_MSTR](
	[ROWID] [uniqueidentifier] NULL DEFAULT (newid()),
	[CLMHDR_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_CLAIM_NBR] [numeric](18, 0) NULL,
	[CLMHDR_ADJ_OMA_CD] [varchar](4) NULL,
	[CLMHDR_ADJ_OMA_SUFF] [varchar](1) NULL,
	[CLMHDR_ADJ_ADJ_NBR] [varchar](1) NULL,
	[CLMHDR_BATCH_TYPE] [varchar](1) NULL,
	[CLMHDR_ADJ_CD_SUB_TYPE] [varchar](1) NULL,
	[CLMHDR_DOC_NBR_OHIP] [varchar](6) NULL,
	[CLMHDR_DOC_SPEC_CD] [numeric](18, 0) NULL,
	[CLMHDR_REFER_DOC_NBR] [numeric](18, 0) NULL,
	[CLMHDR_DIAG_CD] [numeric](18, 0) NULL,
	[CLMHDR_LOC] [varchar](4) NULL,
	[CLMHDR_HOSP] [varchar](1) NULL,
	[CLMHDR_AGENT_CD] [numeric](18, 0) NULL,
	[CLMHDR_ADJ_CD] [varchar](1) NULL,
	[CLMHDR_TAPE_SUBMIT_IND] [varchar](1) NULL,
	[CLMHDR_I_O_PAT_IND] [varchar](1) NULL,
	[CLMHDR_PAT_KEY_TYPE] [varchar](1) NULL,
	[CLMHDR_PAT_KEY_DATA] [varchar](15) NULL,
	[CLMHDR_PAT_ACRONYM6] [varchar](6) NULL,
	[CLMHDR_PAT_ACRONYM3] [varchar](3) NULL,
	[CLMHDR_REFERENCE] [varchar](11) NULL,
	[CLMHDR_DATE_ADMIT] [varchar](8) NULL,
	[CLMHDR_DOC_DEPT] [numeric](18, 0) NULL,
	[CLMHDR_MSG_NBR] [varchar](2) NULL,
	[CLMHDR_REPRINT_FLAG] [varchar](1) NULL,
	[CLMHDR_SUB_NBR] [varchar](1) NULL,
	[CLMHDR_AUTO_LOGOUT] [varchar](1) NULL,
	[CLMHDR_FEE_COMPLEX] [varchar](1) NULL,
	[FILLER] [varchar](2) NULL,
	[CLMHDR_CURR_PAYMENT] [numeric](18, 0) NULL,
	[CLMHDR_DATE_PERIOD_END] [numeric](18, 0) NULL,
	[CLMHDR_CYCLE_NBR] [numeric](18, 0) NULL,
	[CLMHDR_DATE_SYS] [varchar](8) NULL,
	[CLMHDR_AMT_TECH_BILLED] [numeric](18, 0) NULL,
	[CLMHDR_AMT_TECH_PAID] [numeric](18, 0) NULL,
	[CLMHDR_TOT_CLAIM_AR_OMA] [numeric](18, 0) NULL,
	[CLMHDR_TOT_CLAIM_AR_OHIP] [numeric](18, 0) NULL,
	[CLMHDR_MANUAL_AND_TAPE_PAYMENTS] [numeric](18, 0) NULL,
	[CLMHDR_STATUS_OHIP] [varchar](2) NULL,
	[CLMHDR_MANUAL_REVIEW] [varchar](1) NULL,
	[CLMHDR_SUBMIT_DATE] [numeric](18, 0) NULL,
	[CLMHDR_CONFIDENTIAL_FLAG] [varchar](1) NULL,
	[CLMHDR_SERV_DATE] [numeric](18, 0) NULL,
	[CLMHDR_ELIG_ERROR] [varchar](3) NULL,
	[CLMHDR_ELIG_STATUS] [varchar](1) NULL,
	[CLMHDR_SERV_ERROR] [varchar](3) NULL,
	[CLMHDR_SERV_STATUS] [varchar](1) NULL,
	[CLMHDR_ORIG_BATCH_NBR] [varchar](8) NULL,
	[CLMHDR_ORIG_CLAIM_NBR] [numeric](18, 0) NULL,
	[CLMDTL_BATCH_NBR] [varchar](8) NULL,
	[CLMDTL_CLAIM_NBR] [numeric](18, 0) NULL,
	[CLMDTL_OMA_CD] [varchar](4) NULL,
	[CLMDTL_OMA_SUFF] [varchar](1) NULL,
	[CLMDTL_ADJ_NBR] [numeric](18, 0) NULL,
	[CLMDTL_REV_GROUP_CD] [varchar](3) NULL,
	[CLMDTL_AGENT_CD] [numeric](18, 0) NULL,
	[CLMDTL_ADJ_CD] [varchar](1) NULL,
	[CLMDTL_NBR_SERV] [numeric](18, 0) NULL,
	[CLMDTL_SV_YY] [numeric](18, 0) NULL,
	[CLMDTL_SV_MM] [numeric](18, 0) NULL,
	[CLMDTL_SV_DD] [numeric](18, 0) NULL,
	[CLMDTL_SV_NBR1] [numeric](18, 0) NULL,
	[CLMDTL_SV_NBR2] [numeric](18, 0) NULL,
	[CLMDTL_SV_NBR3] [numeric](18, 0) NULL,
	[CLMDTL_SV_DAY1] [numeric](18, 0) NULL,
	[CLMDTL_SV_DAY2] [numeric](18, 0) NULL,
	[CLMDTL_SV_DAY3] [numeric](18, 0) NULL,
	[CLMDTL_SV_NBR_1] [numeric](18, 0) NULL,
	[CLMDTL_SV_DAY_1] [numeric](18, 0) NULL,
	[CLMDTL_SV_NBR_2] [numeric](18, 0) NULL,
	[CLMDTL_SV_DAY_2] [numeric](18, 0) NULL,
	[CLMDTL_SV_NBR_3] [numeric](18, 0) NULL,
	[CLMDTL_SV_DAY_3] [numeric](18, 0) NULL,
	[CLMDTL_AMT_TECH_BILLED] [numeric](18, 0) NULL,
	[CLMDTL_FEE_OMA] [numeric](18, 0) NULL,
	[CLMDTL_FEE_OHIP] [numeric](18, 0) NULL,
	[CLMDTL_DATE_PERIOD_END] [varchar](8) NULL,
	[CLMDTL_CYCLE_NBR] [numeric](18, 0) NULL,
	[CLMDTL_DIAG_CD] [numeric](18, 0) NULL,
	[CLMDTL_LINE_NO] [numeric](18, 0) NULL,
	[CLMDTL_RESUBMIT_FLAG] [varchar](1) NULL,
	[CLMDTL_RESERVE_FOR_FUTURE] [varchar](3) NULL,
	[CLMDTL_DESC] [varchar](22) NULL,
	[CLMDTL_FILLER9] [varchar](104) NULL,
	[CLMDTL_ORIG_BATCH_NBR] [varchar](8) NULL,
	[CLMDTL_ORIG_CLAIM_NBR_IN_BATCH] [numeric](18, 0) NULL,
	[CLMDTL_FILLER0] [varchar](42) NULL,
	[KEY_CLM_TYPE] [varchar](1) NULL,
	[KEY_CLM_BATCH_NBR] [varchar](8) NULL,
	[KEY_CLM_CLAIM_NBR] [numeric](18, 0) NULL,
	[KEY_CLM_SERV_CODE] [varchar](5) NULL,
	[KEY_CLM_ADJ_NBR] [varchar](1) NULL,
	[KEY_P_CLM_TYPE] [varchar](1) NULL,
	[KEY_P_CLM_DATA] [varchar](16) NULL,
	[CHECKSUM_VALUE] [int] NULL DEFAULT ((0))
) ON [PRIMARY]

/****** Object:  Index [F002_CLAIMS_MSTR_KEY_CLAIMS_MSTR]    Script Date: 5/25/2017 11:55:55 AM ******/
CREATE NONCLUSTERED INDEX [F002_CLAIMS_MSTR_KEY_CLAIMS_MSTR] ON [INDEXED].[F002_CLAIMS_MSTR]
(
	[KEY_CLM_TYPE] ASC,
	[KEY_CLM_BATCH_NBR] ASC,
	[KEY_CLM_CLAIM_NBR] ASC,
	[KEY_CLM_SERV_CODE] ASC,
	[KEY_CLM_ADJ_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

/****** Object:  Index [F002_CLAIMS_MSTR_KEY_P_CLAIMS_MSTR]    Script Date: 5/25/2017 11:55:55 AM ******/
CREATE NONCLUSTERED INDEX [F002_CLAIMS_MSTR_KEY_P_CLAIMS_MSTR] ON [INDEXED].[F002_CLAIMS_MSTR]
(
	[KEY_P_CLM_TYPE] ASC,
	[KEY_P_CLM_DATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

END
ELSE
BEGIN
TRUNCATE TABLE [INDEXED].[F002_CLAIMS_MSTR]
END

SET ANSI_PADDING OFF






