IF EXISTS(SELECT * FROM sys.sysdatabases WHERE NAME = '%DatabaseName%')
BEGIN
  ALTER DATABASE [%DatabaseName%]
    SET OFFLINE WITH ROLLBACK IMMEDIATE;

  ALTER DATABASE [%DatabaseName%]
    SET ONLINE WITH ROLLBACK IMMEDIATE
END