USE [RMA_STAGING]

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK1')
  EXEC sp_executesql N'CREATE SCHEMA [DISK1]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK2')
  EXEC sp_executesql N'CREATE SCHEMA [DISK2]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK3')
  EXEC sp_executesql N'CREATE SCHEMA [DISK3]'
  
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK4')
  EXEC sp_executesql N'CREATE SCHEMA [DISK4]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK5')
  EXEC sp_executesql N'CREATE SCHEMA [DISK5]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK6')
  EXEC sp_executesql N'CREATE SCHEMA [DISK6]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK7')
  EXEC sp_executesql N'CREATE SCHEMA [DISK7]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK8')
  EXEC sp_executesql N'CREATE SCHEMA [DISK8]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK9')
  EXEC sp_executesql N'CREATE SCHEMA [DISK9]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DISK10')
  EXEC sp_executesql N'CREATE SCHEMA [DISK10]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR1')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR1]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR2')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR2]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR3')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR3]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR4')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR4]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR5')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR5]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR6')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR6]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR7')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR7]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR8')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR8]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR9')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR9]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR10')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR10]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR11')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR11]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR12')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR12]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR13')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR13]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR14')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR14]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR15')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR15]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR16')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR16]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR17')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR17]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR18')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR18]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR19')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR19]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR20')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR20]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR21')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR21]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR21')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR21]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'OSCAR21')
  EXEC sp_executesql N'CREATE SCHEMA [OSCAR21]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB1')
  EXEC sp_executesql N'CREATE SCHEMA [WEB1]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB2')
  EXEC sp_executesql N'CREATE SCHEMA [WEB2]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB3')
  EXEC sp_executesql N'CREATE SCHEMA [WEB3]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB4')
  EXEC sp_executesql N'CREATE SCHEMA [WEB4]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB5')
  EXEC sp_executesql N'CREATE SCHEMA [WEB5]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB6')
  EXEC sp_executesql N'CREATE SCHEMA [WEB6]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB7')
  EXEC sp_executesql N'CREATE SCHEMA [WEB7]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB8')
  EXEC sp_executesql N'CREATE SCHEMA [WEB8]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB9')
  EXEC sp_executesql N'CREATE SCHEMA [WEB9]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB10')
  EXEC sp_executesql N'CREATE SCHEMA [WEB10]'

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'WEB11')
  EXEC sp_executesql N'CREATE SCHEMA [WEB11]'

