USE [%DatabaseName%]

/****** Object:  Table [TEMPORARYDATA].[CHECKSUM_IDS]    Script Date: 5/25/2017 6:17:14 PM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TEMPORARYDATA].[CHECKSUM_IDS]') AND type in (N'U'))
BEGIN
DROP TABLE [TEMPORARYDATA].[CHECKSUM_IDS]
END
CREATE TABLE [TEMPORARYDATA].[CHECKSUM_IDS](
	[ID] [int] NULL,
	[NEXTVAL] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]
