USE [%DatabaseName%]

/****** Object:  Table [dbo].[CHECKSUM_IDS]    Script Date: 5/25/2017 6:14:14 PM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DIRECT].[CHECKSUM_IDS]') AND type in (N'U'))
BEGIN
DROP TABLE [DIRECT].[CHECKSUM_IDS]
END
CREATE TABLE [DIRECT].[CHECKSUM_IDS](
	[ID] [int] NULL,
	[NEXTVAL] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[CHECKSUM_IDS]    Script Date: 5/25/2017 6:14:14 PM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DIRECT].[RUN_DATE]') AND type in (N'U'))
BEGIN
DROP TABLE [DIRECT].[RUN_DATE]
END
CREATE TABLE [DIRECT].[RUN_DATE](
	[DATE_YYMM] [bigint] NULL
) ON [PRIMARY]
