date
$cmd/update_batch_status_22
$cmd/update_batch_status_23
$cmd/update_batch_status_24
$cmd/update_batch_status_25
$cmd/update_batch_status_26
$cmd/update_batch_status_30
$cmd/update_batch_status_31
$cmd/update_batch_status_32
$cmd/update_batch_status_33
$cmd/update_batch_status_34
$cmd/update_batch_status_35
$cmd/update_batch_status_36
$cmd/update_batch_status_41
$cmd/update_batch_status_42
$cmd/update_batch_status_43
$cmd/update_batch_status_44
$cmd/update_batch_status_45
$cmd/update_batch_status_46
#$cmd/update_batch_status_48
$cmd/update_batch_status_98
date
