CB2-READ-CLAIM-NEXT-FOR-INDEX.

    READ CLAIMS-MSTR-PAT-ACCESS NEXT
        AT END 
            MOVE "Y" TO END-SEARCH-INDEX.

    IF 	HOLD-PAT-KEY-DATA NOT = PAT-ACCESS-PAT-KEY-DATA
    THEN
        MOVE "Y" TO END-SEARCH-INDEX
    ELSE
	NEXT SENTENCE.
*   ENDIF

    RETRIEVE CLAIMS-MSTR-PAT-ACCESS KEY FIX POSITION
    INTO KEY-CLAIMS-MSTR-PAT-ACCESS.


CB2-99-EXIT.
    EXIT.
