01  KEY-APPOINT-RECON-MSTR.
    05  KEY-APPT-DATA.
	10  KEY-APPT-CLINIC-NBR			PIC XX.
*	10  KEY-APPT-DOCTOR-NBR 		PIC 9(4).
	10  KEY-APPT-DOCTOR-NBR.		
	    15  KEY-FILLER-ZERO			PIC 9.
	    15  KEY-APPT-DOC-NBR		PIC 9(3).
	10  KEY-APPT-CHART-OHIP.
	    15  KEY-APPT-PAT-ID-IND		PIC X.
	    15  KEY-APPT-CHART.
	    	20  KEY-APPT-CHART-ALPHA	PIC X.
	    	20  KEY-APPT-CHART-NBRS 	PIC X(11).
	10  KEY-APPT-SERVICE-DATE		PIC X(6).
