
01  TAPEOUT-TRAILER-REC.

    05  TAPEOUT-TRAILER-VALUE-HEE		PIC X(3).
    05  TAPEOUT-TRAILER-CLMHDR1-CNT		PIC 9(4).
    05  TAPEOUT-TRAILER-CLMHDR2-CNT		PIC 9(4).
    05  TAPEOUT-TRAILER-ITM-CNT			PIC 9(5).
    05  TAPEOUT-TRAILER-PAT-ADDR-CNT		PIC 9(4).
    05  FILLER					PIC X(59).
