copy AUDITORS_PAYEFT_YTD.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy CHECKF020_ACTIVE_DOC.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy COSTING_F119HIST.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy DOCINFO.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy DRCHAUDHARY_REJECTS.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy EMERGENCY_PAYROLL_CLMHDRID.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy EMERGENCY_PAYROLL_CLMHDRID.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy EMERGENCY_PAYROLL_CLMHDRID.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy F087_PEDS_REJECTS_BY_ERRCODE.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy F119HIST_AFPADJ_AFPCON.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy F119TITHE.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy G271_CODE.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy GERIATRIC.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy K037_CODE.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy MARYSHIFT.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy TITHE3.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy WEBHST.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
copy YASCLARE.qzs C:\Clients\RMA\GoldApr282017\ParsedCode\yas\quiz
