del apigo.log
del *.api
del metric.dat
del metric.det
del auxiliary.txt

path=C:\CoreProjects\parser\bin;%path%

quiz rmaBilling audit_f050hist.pre audit_f050hist.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling audit_f050tphist.pre audit_f050tphist.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling auditdoc.pre auditdoc.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling billinglist.pre billinglist.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling check_f001_f002_all.pre check_f001_f002_all.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling check_susp_dtl.pre check_susp_dtl.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling checkf001_f090.pre checkf001_f090.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling costing1.pre costing1.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling costing10.pre costing10.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling costing11.pre costing11.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling costing6a_man_rej_dtl.pre costing6a_man_rej_dtl.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling costrev26.pre costrev26.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling create_claims_sub.pre create_claims_sub.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling debugu114.pre debugu114.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling debugu116.pre debugu116.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling diffamt.pre diffamt.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling diffdate.pre diffdate.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling docrev.pre docrev.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling docrevall.pre docrevall.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling dump_tech.pre dump_tech.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling dumpf119.pre dumpf119.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling dumpf119ytd.pre dumpf119ytd.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling kathyf001status.pre kathyf001status.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling maria_rejects3.pre maria_rejects3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling news_email.pre news_email.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling paycode1A_ceilings.pre paycode1A_ceilings.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling payeft.pre payeft.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling payrolllist.pre payrolllist.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004a.pre r004a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004atp.pre r004atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004atp_70.pre r004atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004b.pre r004b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004btp.pre r004btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004btp_70.pre r004btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004btp_portal.pre r004btp_portal.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004c.pre r004c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004c_portal.pre r004c_portal.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004c_portal_ss.pre r004c_portal_ss.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004ctp.pre r004ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004ctp_70.pre r004ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004d.pre r004d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004dtp.pre r004dtp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r004dtp_70.pre r004dtp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005_csv.pre r005_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005atp.pre r005atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005atp_70.pre r005atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005btp.pre r005btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005btp_70.pre r005btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005ctp.pre r005ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005ctp_70.pre r005ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005dtp.pre r005dtp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r005dtp_70.pre r005dtp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006atp.pre r006atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006atp_70.pre r006atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006btp.pre r006btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006btp_70.pre r006btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006ctp.pre r006ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006ctp_70.pre r006ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006dtp.pre r006dtp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r006dtp_70.pre r006dtp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r010cycle.pre r010cycle.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r010daily.pre r010daily.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011_csv.pre r011_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011a.pre r011a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011a_70.pre r011a_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011b.pre r011b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011b_70.pre r011b_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011c.pre r011c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011c_70.pre r011c_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r011mohr.pre r011mohr.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r012atp.pre r012atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r012atp_70.pre r012atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r012btp.pre r012btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r012btp_70.pre r012btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r012ctp.pre r012ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r012ctp_70.pre r012ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r013atp.pre r013atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r013atp_70.pre r013atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r013btp.pre r013btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r013btp_70.pre r013btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r013ctp.pre r013ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r013ctp_70.pre r013ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r015atp.pre r015atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r015atp_70.pre r015atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r015btp.pre r015btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r015btp_70.pre r015btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r015ctp.pre r015ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r015ctp_70.pre r015ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r020a.pre r020a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r020d.pre r020d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r020e.pre r020e.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r020f.pre r020f.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r021a.pre r021a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r021b.pre r021b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r021c.pre r021c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a2.pre r022a2.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a3.pre r022a3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a4.pre r022a4.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a5.pre r022a5.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a6.pre r022a6.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a7.pre r022a7.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a9.pre r022a9.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022d.pre r022d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022e.pre r022e.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022f.pre r022f.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022g.pre r022g.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030d.pre r030d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030e.pre r030e.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030f.pre r030f.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030h.pre r030h.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030i.pre r030i.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030i_2.pre r030i_2.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030i_3.pre r030i_3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030j.pre r030j.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030k.pre r030k.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030k_csv.pre r030k_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030l.pre r030l.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030m.pre r030m.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030n.pre r030n.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030q.pre r030q.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r030r.pre r030r.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r031_before_update.pre r031_before_update.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r031_part2_before_update.pre r031_part2_before_update.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r031a.pre r031a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r031a_agep.pre r031a_agep.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r031b_agep.pre r031b_agep.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r031c.pre r031c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r035b.pre r035b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051a_tp_per.pre r051a_tp_per.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051a_tp_per_70.pre r051a_tp_per_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051b_tp_per.pre r051b_tp_per.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051b_tp_per_70.pre r051b_tp_per_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051ca_portal.pre r051ca_portal.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051caatp.pre r051caatp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051caatp_70.pre r051caatp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cabtp.pre r051cabtp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cabtp_70.pre r051cabtp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cactp.pre r051cactp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cactp_70.pre r051cactp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cb_portal.pre r051cb_portal.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cbatp.pre r051cbatp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cbatp_70.pre r051cbatp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cbbtp.pre r051cbbtp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cbbtp_70.pre r051cbbtp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cbctp.pre r051cbctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r051cbctp_70.pre r051cbctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070_csv.pre r070_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070atp.pre r070atp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070atp_70.pre r070atp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070btp.pre r070btp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070btp_70.pre r070btp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070ctp.pre r070ctp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070ctp_70.pre r070ctp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070dtp.pre r070dtp.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r070dtp_70.pre r070dtp_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r085a.pre r085a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r085e.pre r085e.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r086.pre r086.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r087.pre r087.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r088.pre r088.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r088a.pre r088a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r089.pre r089.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r089_portal.pre r089_portal.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r093.pre r093.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r095.pre r095.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r099.pre r099.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r111b.pre r111b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r112_csv.pre r112_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r113.pre r113.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r119a.pre r119a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r119b.pre r119b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r119c.pre r119c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r120.pre r120.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121a.pre r121a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121a_summ.pre r121a_summ.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121b.pre r121b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121b_company.pre r121b_company.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121b_summ.pre r121b_summ.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121c.pre r121c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r121c_summ.pre r121c_summ.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r123d.pre r123d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r124a.pre r124a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r124a_xls.pre r124a_xls.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r124b_rma.pre r124b_rma.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r124b_xls.pre r124b_xls.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r125.pre r125.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r132.pre r132.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r133.pre r133.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r135.pre r135.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r136.pre r136.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r137.pre r137.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r138_csv.pre r138_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r139_csv.pre r139_csv.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a1f.pre r140_a1f.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a2g.pre r140_a2g.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a2s.pre r140_a2s.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a3.pre r140_a3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a3c.pre r140_a3c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a4.pre r140_a4.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a4t.pre r140_a4t.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_a5.pre r140_a5.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_b2.pre r140_b2.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_b3.pre r140_b3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140_e.pre r140_e.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r140w3.pre r140w3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r141b.pre r141b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r141d.pre r141d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r151.pre r151.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r151d.pre r151d.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r702.pre r702.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r707.pre r707.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r709a.pre r709a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r709b.pre r709b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r710.pre r710.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r712.pre r712.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r716a.pre r716a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r716b.pre r716b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r716c.pre r716c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r717.pre r717.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r801a.pre r801a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r801b.pre r801b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r801c.pre r801c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r921b.pre r921b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r950a.pre r950a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r950b.pre r950b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r950c.pre r950c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r990.pre r990.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997.pre r997.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997_clinic22_84J.pre r997_clinic22_84J.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997_paid.pre r997_paid.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997_portal.pre r997_portal.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997_portal_ss.pre r997_portal_ss.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997_summary.pre r997_summary.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997_total.pre r997_total.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r997a.pre r997a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling rmaprice.pre rmaprice.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling ru701_acr.pre ru701_acr.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling signaturelabels.pre signaturelabels.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling solo_payments.pre solo_payments.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_agent.pre suspend_agent.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_agent_detail.pre suspend_agent_detail.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_desc.pre suspend_desc.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_dtl.pre suspend_dtl.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_status.pre suspend_status.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_suffix.pre suspend_suffix.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling suspend_total.pre suspend_total.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling t4a_addrlabels_1.pre t4a_addrlabels_1.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling t4a_addrlabels_2.pre t4a_addrlabels_2.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling t4a_addrlabels_3.pre t4a_addrlabels_3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling u030aa3.pre u030aa3.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling u100.pre u100.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling u100_b.pre u100_b.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling u100_c.pre u100_c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling u111a.pre u111a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling u140_k.pre u140_k.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl00013.pre utl00013.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0004.pre utl0004.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0006.pre utl0006.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0006_70.pre utl0006_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0006a.pre utl0006a.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0006a_70.pre utl0006a_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0007.pre utl0007.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0007_70.pre utl0007_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0007a_70.pre utl0007a_70.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0012.pre utl0012.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0012c.pre utl0012c.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0021.pre utl0021.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0101.pre utl0101.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0201.pre utl0201.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling utl0f020_ohip_sin.pre utl0f020_ohip_sin.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling web_before_after.pre web_before_after.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling webomafee.pre webomafee.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling webpatients.pre webpatients.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling webpatients_doc.pre webpatients_doc.api /METRIC=metric.dat /LOG=apigo.log

rem These Quiz gpf at write_subfile. To Investigate. 
rem If db.dat is commented out, it works. Do this for now.
rem
del ..\db.dat
quiz rmaBilling r134.pre r134.api /METRIC=metric.dat /LOG=apigo.log
quiz rmaBilling r022a8.pre r022a8.api /METRIC=metric.dat /LOG=apigo.log
copy ..\db3.dat ..\db.dat

