'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ExceptionManagerText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Core.ExceptionManagement.ExceptionManagerText", GetType(ExceptionManagerText).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Publisher failed to execute..
        '''</summary>
        Friend Shared ReadOnly Property RES_CUSTOM_PUBLISHER_FAILURE_MESSAGE() As String
            Get
                Return ResourceManager.GetString("RES_CUSTOM_PUBLISHER_FAILURE_MESSAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The event source {0} does not exist and cannot be created with the current permissions..
        '''</summary>
        Friend Shared ReadOnly Property RES_DEFAULTPUBLISHER_EVENTLOG_DENIED() As String
            Get
                Return ResourceManager.GetString("RES_DEFAULTPUBLISHER_EVENTLOG_DENIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error loading exceptionManagement configuration..
        '''</summary>
        Friend Shared ReadOnly Property RES_EXCEPTION_LOADING_CONFIGURATION() As String
            Get
                Return ResourceManager.GetString("RES_EXCEPTION_LOADING_CONFIGURATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information could not be accessed..
        '''</summary>
        Friend Shared ReadOnly Property RES_EXCEPTIONMANAGEMENT_INFOACCESS_EXCEPTION() As String
            Get
                Return ResourceManager.GetString("RES_EXCEPTIONMANAGEMENT_INFOACCESS_EXCEPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permission Denied.
        '''</summary>
        Friend Shared ReadOnly Property RES_EXCEPTIONMANAGEMENT_PERMISSION_DENIED() As String
            Get
                Return ResourceManager.GetString("RES_EXCEPTIONMANAGEMENT_PERMISSION_DENIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception Manager could not serialize the Exception information into XML..
        '''</summary>
        Friend Shared ReadOnly Property RES_EXCEPTIONMANAGEMENT_XMLSERIALIZATION_EXCEPTION() As String
            Get
                Return ResourceManager.GetString("RES_EXCEPTIONMANAGEMENT_XMLSERIALIZATION_EXCEPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExceptionManagerInternalException.
        '''</summary>
        Friend Shared ReadOnly Property RES_EXCEPTIONMANAGER_INTERNAL_EXCEPTIONS() As String
            Get
                Return ResourceManager.GetString("RES_EXCEPTIONMANAGER_INTERNAL_EXCEPTIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExceptionManagerPublishedException.
        '''</summary>
        Friend Shared ReadOnly Property RES_EXCEPTIONMANAGER_PUBLISHED_EXCEPTIONS() As String
            Get
                Return ResourceManager.GetString("RES_EXCEPTIONMANAGER_PUBLISHED_EXCEPTIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdditionalInformationProperty.
        '''</summary>
        Friend Shared ReadOnly Property RES_XML_ADDITIONAL_INFORMATION() As String
            Get
                Return ResourceManager.GetString("RES_XML_ADDITIONAL_INFORMATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception.
        '''</summary>
        Friend Shared ReadOnly Property RES_XML_EXCEPTION() As String
            Get
                Return ResourceManager.GetString("RES_XML_EXCEPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ExceptionInformation.
        '''</summary>
        Friend Shared ReadOnly Property RES_XML_ROOT() As String
            Get
                Return ResourceManager.GetString("RES_XML_ROOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StackTrace.
        '''</summary>
        Friend Shared ReadOnly Property RES_XML_STACK_TRACE() As String
            Get
                Return ResourceManager.GetString("RES_XML_STACK_TRACE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
