#! /bin/ksh -f

BEGIN {
FileNbr=000
# directory = ENVIRON [ "dvlp" ]
  directory = "." 
  renamefile  = sprintf("%s/renamefile.cli" , directory)
  restorefile = sprintf("%s/restorefile.cli", directory)
  printf "# auto-generated by renameto8.com\n" >renamefile
  printf "# auto-generated by renameto8.com\n" >restorefile
}

{
$0 = tolower($0)

# select only those lines with 1 field
if (NF == 1)
 {
  FileName=$1
  FileNbr=FileNbr+1
  if      (FileNbr > 99) {FileNbrCnt=FileNbr}
  else if (FileNbr >  9) {FileNbrCnt="0" FileNbr}
  else                  {FileNbrCnt="00" FileNbr}
  printf "rename %s file%s    \n",FileName,FileNbrCnt >>renamefile
  printf "mv file%s %s        \n",FileNbrCnt,FileName >>restorefile
 }
else
 {
 }
}
