#!/bin/ksh
#file: 81y2k_reports 
echo Running \'81y2k_reports\'
echo 
echo NOTE: Run \'generate_81y2k_payroll\' in \'ICU Payroll Environment\' 
echo       after this process completes
echo

# ensure running in correct environment
echo 

echo
echo
echo  Starting run ..... `date "+%T"`
##########rm f119.sf* 1>/dev/null 2<&1

echo  create icu-app-file
echo 

rm   icu_app_file.dat icu_app_file_explode.dat 	1>/dev/null 2>&1 

echo "Creating icu-app-file ..."
echo " "
qutil << QUTIL_EXIT
create file icu-app-file
create file icu-app-file-explode
QUTIL_EXIT

rm  icuapp.sf* u933a.sf* u933a.sf*	1>/dev/null 2>&1 
rm  r934*.txt				1>/dev/null 2>&1 

echo "Running u931_temp ..."
echo " "
qtp auto=$obj/u931_temp.qtc

rm  qkin.txt qkout.txt qkecho.txt	1>/dev/null 2>&1 

touch qkin.txt
touch qkout.txt
touch qkecho.txt

#quick auto=$obj/icuapp.qkg term=d410 notermpoll
echo "Running m932.qkc ..."
echo " "
quick auto=$obj/m932.qkc term=vt100

qtp  auto=$obj/u933a_part1.qtc 

echo  Finished Time `date "+%T"`
