#!/bin/ksh
echo  "BACKUP_NIGHTLY"
echo  
#echo  'HIT   "NEWLINE"   TO COMMENCE BACKUP ...'
#read garbage

echo 
echo  BACKUP NOW COMMENCING ...
echo 
echo  
date 
echo  

cd  $application_root
# remove flag that indicates job finished successfully
rm backup_nightly.flg 1>/dev/null 2>&1

pwd
/bin/ls                      \
production/moh*              \
production/yasemin/*         \
production/web/*             \
production/web1/*            \
production/web2/*            \
production/web3/*            \
production/web4/*            \
production/web5/*            \
production/web6/*            \
production/web7/*            \
production/web8/*            \
production/web9/*            \
production/web10/*           \
production/diskette/*        \
production/diskette1/*       \
production/stone/*           \
production/kathy/*           \
production/mumc/*            \
production/*parm*            \
production/23/*parm*         \
production/31/*parm*         \
production/32/*parm*         \
production/33/*parm*         \
production/34/*parm*         \
production/35/*parm*         \
production/36/*parm*         \
production/37/*parm*         \
production/41/*parm*         \
production/42/*parm*         \
production/43/*parm*         \
production/44/*parm*         \
production/45/*parm*         \
production/46/*parm*         \
production/47/*parm*         \
production/48/*parm*         \
production/60/rm*            \
production/70/*parm*         \
production/70/rm*            \
production/80/*parm*         \
production/80/rm*            \
production/81/*parm*         \
production/81/rm*            \
production/82/*parm*         \
production/82/rm*            \
production/83/*parm*         \
production/83/rm*            \
production/85/*parm*         \
production/85/rm*            \
production/91/*parm*         \
production/91/rm*            \
production/92/*parm*         \
production/92/rm*            \
production/93/*parm*         \
production/93/rm*            \
production/94/*parm*         \
production/94/rm*            \
production/95/*parm*         \
production/95/rm*            \
production/96/*parm*         \
production/96/rm*            \
production/98/*parm*         \
production/98/rm*            \
production/*parm*            \
production/rm*               \
production/aug14*            \
production/oct13*            \
production/sep16*            \
production/f002_suspend*     \
production/u010*             \
production/*u993*            \
production/icuapp*           \
production/r010*             \
production/f086*              > data/nightly.ls
echo 
echo 
date


echo "Finding directories with sub directories and files..."
cd /
pwd
find /alpha/rmabill/rmabill101c/backups/*.ls  -print >> $pb_data/nightly.ls
find /alpha/home/rma*                         -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/data/*        -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/batch/*       -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/cmd/*         -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/doc/*         -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/use/*         -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/src/*         -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/data2/*       -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/dvlp/*        -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101c/obj/*         -print >> $pb_data/nightly.ls
find /macros/*                                -print >> $pb_data/nightly.ls
find /etc/*                                   -print >> $pb_data/nightly.ls
find /alpha/rmabill/rmabill101/dvlp/*         -print >> $pb_data/nightly.ls 
#find /alpha/rmabill/rmabill81y2k/data/*       -print >> $pb_data/nightly.ls 
#find /alpha/rmabill/rmabill81y2k/data2/*      -print >> $pb_data/nightly.ls 
#find /alpha/rmabill/rmabill81y2k/dvlp/*       -print >> $pb_data/nightly.ls  
find /alpha/rmabill/rmabillicu/data/*         -print >> $pb_data/nightly.ls 
find /alpha/rmabill/rmabillicu/data2/*        -print >> $pb_data/nightly.ls 
find /alpha/rmabill/rmabillicu/dvlp/*         -print >> $pb_data/nightly.ls  
find /alpha/rmabill/rmabillmp/dvlp/*          -print >> $pb_data/nightly.ls  
find /alpha/rmabill/rmabillmp/data/*          -print >> $pb_data/nightly.ls  
find /alpha/rmabill/rmabillmp/data2/*         -print >> $pb_data/nightly.ls 
echo 
echo
date

echo "Starting copy of file to tape ..."
cd $application_root
pwd
echo before cat
cat data/nightly.ls  | cpio -ocuvB > /dev/rmt/1
echo after cat
# set flag that indicates job finished successfully
touch backup_nightly.flg 
echo after touch
echo " "
date
echo "DONE!"


#  ***** IF NEW Daily BACKUP ADDED UPDATE BACKUP_DAILY_to_disk  ALSO

echo  
date 
echo  

mt -f /dev/rmt/1 rewind

