#!/bin/ksh
# 2003/dec/08 b.e. removed 101c backup
#
echo  "BACKUP_NIGHTLY_DATA_TO_DYAD"
echo  
#echo  'HIT   "NEWLINE"   TO COMMENCE BACKUP ...'
#read garbage

echo 
echo  BACKUP NOW COMMENCING ...
echo 
echo  
date 
echo  

cd  $application_root
# remove flag that indicates job finished successfully
rm backup_nightly_data_to_dyad.flg 1>/dev/null 2>&1


echo "Finding directories with sub directories and files..."
cd /
pwd
#find /alpha/rmabill/rmabill101c/data/*        -print >  $pb_data/nightly_data_to_dyad.ls
#find /alpha/rmabill/rmabill101c/data2/*       -print >> $pb_data/nightly_data_to_dyad.ls

find /alpha/rmabill/rmabillicu/data/*         -print >  $pb_data/nightly_data_to_dyad.ls 
find /alpha/rmabill/rmabillicu/data2/*        -print >> $pb_data/nightly_data_to_dyad.ls 
find /alpha/rmabill/rmabillmp/data/*          -print >> $pb_data/nightly_data_to_dyad.ls  
find /alpha/rmabill/rmabillmp/data2/*         -print >> $pb_data/nightly_data_to_dyad.ls 
echo 
echo
date

echo "Starting copy of file to tape ..."
cd $application_root
pwd
echo before cat
cat data/nightly_data_to_dyad.ls  | cpio -ocuvB > /dyad/backup_transfer_area/backup_nightly_data.cpio
echo after cat
# set flag that indicates job finished successfully
touch backup_nightly_data_to_dyad.flg 
echo after touch
echo " "
date
echo "DONE!"


#  ***** IF NEW Daily BACKUP ADDED UPDATE BACKUP_DAILY_to_disk  ALSO

echo  
date 
echo  


