#!/bin/ksh
# 2006/oct/11 b.e. removed data2/ma and icu from backups as per yas request
# 2007/nov/14 M.C. modify and correct accordingly based on Yasemin's agreement
#		   101c/data & mp/data are being backup once a week by $cmd/backupdata_101c_mp
# 2007/dec/19 M.C. this macro only backup data2 for 101c and mp, backing up of 3 cpio files
#		   with compress is done in $cmd/backup_dyad_to_tape1

echo  "BACKUP_DYAD_TO_TAPE2"
echo  

echo 
echo  BACKUP NOW COMMENCING ...
echo 
echo  
date 
echo  

mt -f /dev/rmt/1 rewind

cd  $application_root
# remove flag that indicates job finished successfully
echo Removing process flag
rm backup_dyad_to_tape2.flg 1>/dev/null 2>&1

echo Building list of files to backup to TAPE ...
# backup 101c & mp data2 files


find /alpha/rmabill/rmabill101c/data2/ma/*  -print >  $pb_data/backup_dyad_to_tape2.ls
find /alpha/rmabill/rmabillmp/data2/ma/*    -print >> $pb_data/backup_dyad_to_tape2.ls 
echo 
echo
date

cd $application_root
pwd
echo Starting cpio to tape device ...
cat $pb_data/backup_dyad_to_tape2.ls | cpio -ocuvB > /dev/rmt/1

echo Done writing to TAPE
# set flag that indicates job finished successfully
touch backup_dyad_to_tape2.flg 
echo " "

echo  
date 
echo  

echo Rewinding tape ...
mt -f /dev/rmt/1 rewind
echo

date
echo "DONE!"
