#!/bin/ksh
# 2006/oct/11 b.e. removed data2/ma and icu from backups as per yas request
# 2007/nov/14 M.C. modify and correct accordingly based on Yasemin's agreement
#		   101c/data & mp/data are being backup once a week by $cmd/backupdata_101c_mp
# 2008/01/03  yas  comment out ma since we back it up monthly


echo  "BACKUP_DYAD_TO_TAPE"
echo  

echo 
echo  BACKUP NOW COMMENCING ...
echo 
echo  
date 
echo  

mt -f /dev/rmt/1 rewind

cd  $application_root
# remove flag that indicates job finished successfully
echo Removing process flag
rm backup_dyad_to_tape.flg 1>/dev/null 2>&1

echo Building list of files to backup to TAPE ...
# backup non data files
/bin/ls /beta/backup_transfer_area/backup_nightly_part2.cpio 	\
					      > $pb_data/backup_dyad_to_tape.ls
/bin/ls /beta/backup_transfer_area/backup_nightly_part3.cpio 	\
					     >> $pb_data/backup_dyad_to_tape.ls
/bin/ls /beta/backup_transfer_area/backup_nightly_part1.cpio 	\
					     >> $pb_data/backup_dyad_to_tape.ls


#find /alpha/rmabill/rmabill101c/data2/ma/*  -print >> $pb_data/backup_dyad_to_tape.ls
#find /alpha/rmabill/rmabillmp/data2/ma/*    -print >> $pb_data/backup_dyad_to_tape.ls 
echo 
echo
date

#cat data/backup_dyad_to_tape.ls  | cpio -ocuvB | compress -c | dd of=/dev/rmt/1

echo Starting copy to tape device ...

#cat data/backup_dyad_to_tape.ls  | cpio -ocuvB | compress -c | dd of=/dev/rmt/1 
#tar -cv1  -I                     $pb_data/backup_dyad_to_tape.ls 
#tar -cvf -I $pb_data/backup_dyad_to_tape.ls | compress -c | dd of=/dev/rmt/1 
#tar -cvf -I $pb_data/backup_dyad_to_tape.ls | gzip -c | dd of=/dev/rmt/1 
tar -cvf -I $pb_data/backup_dyad_to_tape.ls | gzip -c | dd of=/dev/rmt/1 

echo
date

echo Done writing to TAPE
# set flag that indicates job finished successfully
touch backup_dyad_to_tape.flg 
echo " "

echo  
date 
echo  

echo Rewinding tape ...
mt -f /dev/rmt/1 rewind
echo

date
echo "DONE!"
