#!/bin/ksh
echo  "BACKUP_NIGHTLY_TO_DYAD"
# 2005/jul/18 b.e. added backup of obj and cmd in rmabill mp
echo  

echo 
echo  BACKUP NOW COMMENCING ...
echo 
echo  
date 
echo  

cd  $application_root
# remove flag that indicates job finished successfully
rm backup_nightly_to_dyad.flg 1>/dev/null 2>&1

pwd
/bin/ls                      \
production/moh*              \
production/yasemin/*         \
production/web/*             \
production/web1/*            \
production/web2/*            \
production/web3/*            \
production/web4/*            \
production/web5/*            \
production/web6/*            \
production/web7/*            \
production/web8/*            \
production/web9/*            \
production/web10/*           \
production/diskette/*        \
production/diskette1/*       \
production/stone/*           \
production/kathy/*           \
production/mumc/*            \
production/60/*parm*         \
production/70/*parm*         \
production/80/*parm*         \
production/81/*parm*         \
production/82/*parm*         \
production/83/*parm*         \
production/85/*parm*         \
production/86/*parm*         \
production/91/*parm*         \
production/92/*parm*         \
production/93/*parm*         \
production/94/*parm*         \
production/95/*parm*         \
production/96/*parm*         \
production/98/*parm*         \
production/*parm*            \
production/aug14*            \
production/oct13*            \
production/sep16*            \
production/f002_suspend*     \
production/u010*             \
production/*u993*            \
production/icuapp*           \
production/r010*             \
production/f086*             \
obj/*              > data/nightly_to_dyad.ls
echo 
echo 
date


echo "Finding directories with sub directories and files..."
cd /
pwd
find /alpha/rmabill/rmabill101c/src/*         -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/obj/*         -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/use/*         -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/batch/*       -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/cmd/*         -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/doc/*         -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/dvlp/*        -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101c/backups/*.ls  -print >> $pb_data/nightly_to_dyad.ls
find /alpha/home/rma*                         -print >> $pb_data/nightly_to_dyad.ls
find /macros/*                                -print >> $pb_data/nightly_to_dyad.ls
find /etc/*                                   -print >> $pb_data/nightly_to_dyad.ls
find /alpha/rmabill/rmabill101/dvlp/*         -print >> $pb_data/nightly_to_dyad.ls 
find /alpha/rmabill/rmabill101/src/*          -print >> $pb_data/nightly_to_dyad.ls 
find /alpha/rmabill/rmabillicu/dvlp/*         -print >> $pb_data/nightly_to_dyad.ls  
find /alpha/rmabill/rmabillmp/dvlp/*          -print >> $pb_data/nightly_to_dyad.ls  
find /alpha/rmabill/rmabillmp/src/*           -print >> $pb_data/nightly_to_dyad.ls  
find /alpha/rmabill/rmabillmp/cmd/*           -print >> $pb_data/nightly_to_dyad.ls  
find /alpha/rmabill/rmabillmp/obj/*           -print >> $pb_data/nightly_to_dyad.ls  
echo 
echo
date

echo "Starting copy of file to tape ..."
cd $application_root
pwd
echo before cat
#cat data/nightly_to_dyad.ls  | cpio -ocuvB > /dyad/backup_transfer_area/backup_nightly.cpio
cat data/nightly_to_dyad.ls  | cpio -ocuv > /dyad/backup_transfer_area/backup_nightly.cpio
echo after cat
# set flag that indicates job finished successfully
touch backup_nightly_to_dyad.flg 
echo after touch
echo " "
date
echo "DONE!"

echo  
date 
echo  



