#!/bin/ksh
# 2006/oct/11 b.e. removed data2/ma and icu from backups as per yas request
# 2007/nov/14 M.C. modify and correct accordingly based on Yasemin's agreement
#		   101c/data & mp/data are being backup once a week by $cmd/backupdata_101c_mp
# 2008/01/03  yas  comment out ma since we back it up monthly


echo  "BACKUP_DYAD_TO_TAPE_VERIFY"
echo  
echo 
echo  VERIFY NOW COMMENCING ...
echo  
echo Rewinding tape ...
mt -f /dev/rmt/1 rewind

date
echo starting verify of tape ...
# tar -tv1 >   $pb_data/backup_dyad_to_tape.log
dd if=/dev/rmt/1 | uncompress -c | tar -tvf >  $pb_data/backup_dyad_to_tape.log

echo
echo Done verifying ...
date

echo Comparing lines in .ls vs .log
ls  $pb_data/backup_dyad_to_tape.ls  $pb_data/backup_dyad_to_tape.log 
echo
cat $pb_data/backup_dyad_to_tape.ls  | wc -l
cat $pb_data/backup_dyad_to_tape.log | wc -l

echo
#echo Press Enter to page out verification log
#read garbage
#pg data/backup_daily_complete.log

echo  
date 
echo  

echo Rewinding tape ...
mt -f /dev/rmt/1 rewind
echo

date
echo "DONE!"
