#!/bin/ksh
# 2011/02/17		MC - backup f002 claims, shadow & f071 to disk n /foxtrot/purge before claim purge


echo  "backup_f002_f071_to_disk"
echo  
echo 
echo  BACKUP NOW COMMENCING ...

date 
echo  
echo "Finding directories with sub directories and files..."

cd /
application_root=/alpha/rmabill/rmabill101c
pb_data=$application_root/data

echo "Finding files in '101c' data for f002 files only  ..."
/bin/ls  /alpha/rmabill/rmabill101c/data/f002_claims_mstr.idx            \
		                             > $pb_data/backup_101c_f002.ls
/bin/ls  /alpha/rmabill/rmabill101c/data/f002_claims_mstr                \
		                            >> $pb_data/backup_101c_f002.ls

echo "Finding files in '101c' data for f002 SHDW  only  ..."
/bin/ls  /alpha/rmabill/rmabill101c/data/f002_claim_shadow.idx            \
		                             > $pb_data/backup_101c_shdw.ls
/bin/ls  /alpha/rmabill/rmabill101c/data/f002_claim_shadow               \
		                            >> $pb_data/backup_101c_shdw.ls

echo "Finding files in '101c' data for f071 files only  ..."
/bin/ls  /alpha/rmabill/rmabill101c/data/f071_client_rma_claim_nbr.idx   \
		                             > $pb_data/backup_101c_f071.ls
/bin/ls  /alpha/rmabill/rmabill101c/data/f071_client_rma_claim_nbr       \
		                            >> $pb_data/backup_101c_f071.ls

echo
date

echo "backup to disk commencing ..."

cat $pb_data/backup_101c_f002.ls |cpio -ocuvB | compress -c  > /foxtrot/purge/backup_101c_f002.cpio
cat $pb_data/backup_101c_shdw.ls |cpio -ocuvB | compress -c  > /foxtrot/purge/backup_101c_shdw.cpio
cat $pb_data/backup_101c_f071.ls |cpio -ocuvB | compress -c  > /foxtrot/purge/backup_101c_f071.cpio

echo
date
echo "DONE!"


