#!/bin/ksh
# 2009/02/11		MC - backup all data files to cpio  with compress
# 2009/08/10		MC - include subdirectories of disk1 to disk10 under 101c/production (data/disk*dir.ls)


echo  "backup_all_data_to_disk"
echo  
echo 
echo  BACKUP NOW COMMENCING ...

date 
echo  
echo "Finding directories with sub directories and files..."

cd /
application_root=/alpha/rmabill/rmabill101c
pb_data=$application_root/data


echo "Finding files in '101c' data without sub-directories and f002 and f010 ..."
find /alpha/rmabill/rmabill101c/data/*                          \
           \(   ! -name 'f010_pat_mstr'     	\
                ! -name 'f010_pat_mstr.dat' 	\
                ! -name 'f010_pat_mstr.idx' 	\
                ! -name 'f002_claims_mstr'  	\
                ! -name 'f002_claims_mstr.dat'  \
                ! -name 'f002_claims_mstr.idx'  \
                -prune ! -type d         	\
            \)                         -print  > $pb_data/backup_101c_data.ls


echo "Finding files in '101c' data for f002 files only  ..."
/bin/ls  /alpha/rmabill/rmabill101c/data/f002_claims_mstr.idx            \
		                             > $pb_data/backup_101c_f002.ls
/bin/ls  /alpha/rmabill/rmabill101c/data/f002_claims_mstr                \
		                            >> $pb_data/backup_101c_f002.ls

echo "Finding files in '101c' data for f010 files only  ..."
/bin/ls /charly/rmabill/rmabill101c/data/f010_pat_mstr.idx            \
		                             > $pb_data/backup_101c_f010.ls
/bin/ls /charly/rmabill/rmabill101c/data/f010_pat_mstr                \
		                            >> $pb_data/backup_101c_f010.ls
echo
date

echo "Finding files in 'mp' data without sub-directories ..."
find /alpha/rmabill/rmabillmp/data/*            \
                -prune !  -type d      -print > $pb_data/backup_mp_data.ls

echo
date

echo "Finding files in 'solo' data without sub-directories ..."
find /alpha/rmabill/rmabillsolo/data/*            \
                -prune !  -type d      -print > $pb_data/backup_solo_data.ls

echo
date

echo "Finding files in '101' data without sub-directories ..."
find /alpha/rmabill/rmabill101/data/*            \
                -prune !  -type d      -print > $pb_data/backup_101_data.ls

echo
date

cd $application_root

/bin/ls					\
production/ext*                         \
production/f086*                        \
production/moh_obec*                    \
production/r010*                        \
production/u010*                        > $pb_data/backup_101c_prod.ls

echo "Finding production diskette upload files ..."
cat   $pb_data/diskettedir.ls  \
      $pb_data/diskette1dir.ls  \
      $pb_data/disk1dir.ls  \
      $pb_data/disk2dir.ls  \
      $pb_data/disk3dir.ls  \
      $pb_data/disk4dir.ls  \
      $pb_data/disk5dir.ls  \
      $pb_data/disk6dir.ls  \
      $pb_data/disk7dir.ls  \
      $pb_data/disk8dir.ls  \
      $pb_data/disk9dir.ls  \
      $pb_data/disk10dir.ls  \
      $pb_data/suspend.ls  \
      $pb_data/kathydir.ls  \
      $pb_data/mumcdir.ls  \
      $pb_data/stonedir.ls  \
      $pb_data/webdir.ls  \
      $pb_data/web1dir.ls  \
      $pb_data/web2dir.ls  \
      $pb_data/web3dir.ls  \
      $pb_data/web4dir.ls  \
      $pb_data/web5dir.ls  \
      $pb_data/web6dir.ls  \
      $pb_data/web7dir.ls  \
      $pb_data/web8dir.ls  \
      $pb_data/web9dir.ls  \
      $pb_data/web10dir.ls  \
      $pb_data/yasemin.ls    >> $pb_data/backup_101c_prod.ls 

echo
date

doBackupFlag=Y
echo $doBackupFLag
testCounter=1
while [ $testCounter != 10 ]
do
  if [ -f $pb_data/delay_6pm_backup.flg ]
  then
    doBackupFlag=N
    echo sleeping 1800 seconds or half hour ....
    sleep 1800
    ((testCounter=testCounter+1))
  else
    testCounter=10
    doBackupFlag=Y
  fi
done
echo ending $testCounter
echo ending $doBackupFlag

if  [ "$doBackupFlag" = "Y" ]
then
        echo DO BACKUP - no flag now
echo "backup to disk commencing ..."

cat $pb_data/backup_101c_data.ls |cpio -ocuvB | compress -c  > /charly/backup_transfer_area/backup_101c_data.cpio
cat $pb_data/backup_101c_f002.ls |cpio -ocuvB | compress -c  > /charly/backup_transfer_area/backup_101c_f002.cpio
cat $pb_data/backup_101c_f010.ls |cpio -ocuvB | compress -c  > /charly/backup_transfer_area/backup_101c_f010.cpio
cat $pb_data/backup_101c_prod.ls |cpio -ocuvB | compress -c  > /charly/backup_transfer_area/backup_101c_prod.cpio
cat $pb_data/backup_mp_data.ls   |cpio -ocuvB | compress -c > /charly/backup_transfer_area/backup_mp_data.cpio
cat $pb_data/backup_solo_data.ls |cpio -ocuvB | compress -c > /charly/backup_transfer_area/backup_solo_data.cpio
cat $pb_data/backup_101_data.ls  |cpio -ocuvB | compress -c > /charly/backup_transfer_area/backup_101_data.cpio

echo
date
echo "DONE!"
else
        echo BYPASS backup - still a flag after 10 attempts!
fi


