#! /bin/ksh 
# 2002/01/21 B.E. - original
# 2002/08/28 yas  - change percent to 1.40 as per Leena request      

echo Running "daily_icu_payroll_update"
echo

echo "Creating icu app files ..."
echo " "
qutil << QUTIL_EXIT
create file icu-app-file
create file icu-app-file-explode
QUTIL_EXIT

rm  icuapp.sf* u933a.sf* u933a.sf*      1>/dev/null 2>&1

echo "Running u931_temp ..."
date
echo " "
qtp auto=$obj/u931_temp.qtc

rm  qkin.txt qkout.txt qkecho.txt       1>/dev/null 2>&1

touch qkin.txt
touch qkout.txt
touch qkecho.txt

echo "Running m932.qkc ..."
date
echo " "
quick auto=$obj/m932.qkc term=vt100

echo

echo
echo Running u933a_part1 and u933a_part2
date
qtp << QTP_EXIT1
exec $obj/u933a_part1.qtc
exec $obj/u933a_part2.qtc
0.0
1.40 
QTP_EXIT1

echo
echo date
echo Done!
