#!/bin/ksh
# Kevin Miles -- Tue Jan 20 13:45:10 EST 1998
# length [filespec]
# ie: length *qks or length u030.txt
# produces output of bytes

ls -al $* | awk ' { if (NF > 5) { flds = split($NF, fld, "/")
                   file_name = fld[flds]
                   printf "File length of %s (in bytes) = %7s\n", file_name, $5 } }'
