#!/bin/ksh
# Program: "rat_copy_tape_to_disk:
# Purpose: originally this macro copied the file from tape to disk
#          and converted it from ebcdic to ascii
#	   Now the file is already on disk on the CSU HP in ascii
#	   and must be copied to this machine and converted from
#	   into a fixed length 79 byte record file.
#

echo  "rat_copy_tape_to_disk"
echo  "make sure you are loged under rma's operator username" 

echo  'HIT  "NEWLINE"  TO CONTINUE ...'
 read garbage

echo 
echo 

# ftp the file to CSU's hp computer
#!/bin/ksh
#echo "ftping file to CSU's hp computer ..."
#TERM=vt100; export TERM
#. /etc/profile
#. /alpha/home/rma/.profile

ftp -v csuhpftp << E_O_F
binary
hash
get rattape
quit
E_O_F
echo 
echo "DONE !"

mv rattape ohip_rat_ascii


