#!/bin/ksh
## reload_all_data_from_disk

echo "reload_all_data_from_disk"

date

application_root=/alpha/rmabill/rmabill101c
cd $application_root

## 2009/may/20 - f002 files takes (91% - 58%) = 33% in dyad
## MUST delete the files before reload; otherwise receive error 'No space Left'

uncompress -c < /charly/backup_transfer_area/backup_101c_f002.cpio | cpio -icdvB
date

echo "restore is done"
date


