#!/bin/ksh

## reload_101c_data_from_disk

echo "reload_101c_data_from_disk"

date

cd $application_root

## restore 101c data from disk except f002 & f010 files
uncompress -c  < /charly/backup_transfer_area/backup_101c_data.cpio | cpio -icdvB
## restore 101c f002 data 
uncompress -c  < /charly/backup_transfer_area/backup_101c_f002.cpio | cpio -icdvB
## restore 101c f010 data
uncompress -c  < /charly/backup_transfer_area/backup_101c_f010.cpio | cpio -icdvB

echo "restore is done"
date

