#!/bin/ksh
## reload_subfile_from_disk

echo "reload_subfile_from_disk"

date

application_root=/alpha/rmabill/rmabill101c
cd $pb_data2               

uncompress -c < /charly/backup_transfer_area/backup_subfile_to_disk.cpio | cpio -icdvB
date


echo "restore is done"
date


