#!/bin/ksh
## reload_all_data_from_disk

echo "reload_all_data_from_disk"

date

application_root=/alpha/rmabill/rmabill101c
cd $application_root


## restore mp   data from disk
uncompress -c < /charly/backup_transfer_area/backup_mp_data.cpio | cpio -icdvB
date

## restore solo data from disk
uncompress -c < /charly/backup_transfer_area/backup_solo_data.cpio | cpio -icdvB
date


echo "restore is done"
date


