#! /bin/ksh -f

BEGIN {
FileNbr=000
 ports = ENVIRON [ "dvlp" ]
  FnRename  = sprintf("%s/rename.cli", ports)
  FnRestore = sprintf("%s/restore.com", ports)
  printf "; auto-generated by renameto8.com\n" >FnRename
  printf "; auto-generated by renameto8.com\n" >FnRestore
}

{
$0 = tolower($0)

# select only those lines with 1 field
if (NF == 1)
 {
  FileName=$1
  FileNbr=FileNbr+1
  if      (FileNbr > 99) {FileNbrCnt=FileNbr}
  else if (FileNbr >  9) {FileNbrCnt="0" FileNbr}
  else                  {FileNbrCnt="00" FileNbr}
  printf "rename %s copy%s    \n",FileName,FileNbrCnt >>FnRename
  printf "mv copy%s %s        \n",FileNbrCnt,FileName >>FnRestore
 }
else
 {
 }
}
