#!/bin/ksh
#Macro: run_ohip_stale_claims

echo Running run_ohip_stale_claims IN PROGRESS  `date`  ...

cd $application_production

rm u020_tapeout_file* u020*sf* 2>/dev/null

#######################################

rm u022_tp.sf*
rm u022a?.sf*
rm u022e?.sf*
rm ru022a
rm ru022b
rm ru022
rm ru022mr
rm u022a1*stale*.sf*

qtp auto=$obj/u022a1_stale.qtc 

quiz auto=$obj/r022.qzu 

qtp auto=$obj/u022.qtu

mv ru022a.txt  ru022a_stale
mv ru022b.txt  ru022b_stale
mv ru022.txt   ru022_stale
mv ru022mr.txt ru022mr_stale_before

mv u020_tp.sf   u022_tp_stale.sf
mv u020_tp.sfd  u022_tp_stale.sfd


##  regenerate ru022mr for correct report
quiz << QUIZ_EXIT
exec $obj/r022a7
exec $obj/r022a8
exec $obj/r022a9
QUIZ_EXIT

mv ru022mr.txt ru022mr_stale

##############################################

cat u022_tp_stale.sf          > u020_tapeout_file    2>/dev/null

##$cmd/ohip_convert_copy_to_tape              

echo
date
echo

