#!/bin/ksh
#Macro: run_ohip_resubmit_stale_claims

echo Running run_ohip_resubmit_stale_claims ...

rm u020_tapeout_file* u020*sf* 2>/dev/null

$cmd/u022 0 0
echo
echo
echo

cat u022_tp.sf          > u020_tapeout_file    2>/dev/null
cat sd_u022.sf          >>u020_tapeout_file    2>/dev/null

echo Converting submission data to EDI format
$cmd/convert_submit_tape_to_edi_format

echo
date
echo

