#!/bin/ksh
#run_meditech_upload
# 2002/may/16 B.E. - original

echo running automated job ...

echo `date`
echo $SHELL

echo Setting up Profile ...
. /macros/profile  >> /alpha/rmabill/rmabill101c/upload/run_meditech_upload.log
echo Setting up Environment ...
rmabill 101c        >> /alpha/rmabill/rmabill101c/upload/run_meditech_upload.log
pwd

echo 

cd $application_root
cd production
pwd
echo testing process flag ...
if [ -f run_u011_in_batch.flg ]
then
  echo Running "$cmd/upload_meditech_patients med_down"
  $cmd/upload_meditech_patients med_down
  echo
  echo automated job DONE!
else
  echo Processing Flag NOT found - bypass the running of procedure
fi

