#!/bin/ksh
#Macro: run_ohip_resubmit_tape 

echo Running run_ohip_resubmit_tape ...

rm ru020* u020_tapeout_file* u020_tp.sf* u020*sf* 2>/dev/null

echo "--- u020a (QTP RUN) ---" 
qtp auto=$obj/u020a.qtc 

echo "Processing u020a1_a ..."
if [ -s u020a1_a.sf ]
then

  mv u020a1_a.sf  u020a1.sf
  mv u020a1_a.sfd u020a1.sfd

  $cmd/u020

  mv u020_tp.sf   u020_tapeout_file_a
  rm u020_tp.sfd
  
  mv ru020a.txt	  ru020a_a
  mv ru020b_d.txt ru020b_d_a
  mv ru020b_s.txt ru020b_s_a
  mv ru020c.txt   ru020c_a
  mv ru020mr.txt  ru020mr_a
  mv u020a1.sf    u020a1_a.sf
  mv u020a1.sfd   u020a1_a.sfd
fi
 

echo "Processing u020a1_b ..."
if [ -s u020a1_b.sf ]
then

  mv u020a1_b.sf   u020a1.sf
  mv u020a1_b.sfd  u020a1.sfd

  $cmd/u020

  mv u020_tp.sf u020_tapeout_file_b
  rm u020_tp.sfd

  mv ru020a.txt	  ru020a_b
  mv ru020b_d.txt ru020b_d_b
  mv ru020b_s.txt ru020b_s_b
  mv ru020c.txt   ru020c_b
  mv ru020mr.txt  ru020mr_b
  mv u020a1.sf    u020a1_b.sf
  mv u020a1.sfd   u020a1_b.sfd
fi

echo "Processing u020a1_c ..."
if [ -s u020a1_c.sf ]
then

  mv u020a1_c.sf   u020a1.sf
  mv u020a1_c.sfd  u020a1.sfd

  $cmd/u020

  mv  u020_tp.sf u020_tapeout_file_c
  rm  u020_tp.sfd

  mv  ru020a.txt ru020a_c
  mv  ru020b_d.txt ru020b_d_c
  mv  ru020b_s.txt ru020b_s_c
  mv  ru020c.txt ru020c_c
  mv  ru020mr.txt ru020mr_c
  mv  u020a1.sf   u020a1_c.sf
  mv  u020a1.sfd  u020a1_c.sfd
fi


echo "Processing u020a1_d ..."
if [ -s u020a1_d.sf ]
then

  mv u020a1_d.sf   u020a1.sf
  mv u020a1_d.sfd  u020a1.sfd

  $cmd/u020

  mv u020_tp.sf u020_tapeout_file_d
  rm u020_tp.sfd

  mv ru020a.txt  ru020a_d
  mv ru020b_d.txt ru020b_d_d
  mv ru020b_s.txt ru020b_s_d
  mv ru020c.txt  ru020c_d
  mv ru020mr.txt ru020mr_d
  mv u020a1.sf   u020a1_d.sf
  mv u020a1.sfd  u020a1_d.sfd
fi


echo
echo
echo
cat ru020a_a  > ru020a
cat ru020a_b >> ru020a    2>/dev/null
cat ru020a_c >> ru020a    2>/dev/null
cat ru020a_d >> ru020a    2>/dev/null

cat ru020b_d_a  >ru020b
cat ru020b_s_a >>ru020b    2>/dev/null
cat ru020b_d_b >>ru020b    2>/dev/null
cat ru020b_s_b >>ru020b    2>/dev/null
cat ru020b_d_c >>ru020b    2>/dev/null
cat ru020b_s_c >>ru020b    2>/dev/null
cat ru020b_d_d >>ru020b    2>/dev/null
cat ru020b_s_d >>ru020b    2>/dev/null

cat ru020c_a  >ru020c
cat ru020c_b >>ru020c    2>/dev/null
cat ru020c_c >>ru020c    2>/dev/null
cat ru020c_d >>ru020c    2>/dev/null

cat ru020mr_a  >ru020mr
cat ru020mr_b >>ru020mr    2>/dev/null
cat ru020mr_c >>ru020mr    2>/dev/null
cat ru020mr_d >>ru020mr    2>/dev/null

cat u020_tapeout_file_a  >u020_tapeout_file
cat u020_tapeout_file_b >>u020_tapeout_file    2>/dev/null
cat u020_tapeout_file_c >>u020_tapeout_file    2>/dev/null
cat u020_tapeout_file_d >>u020_tapeout_file    2>/dev/null
cat u022_tp.sf          >>u020_tapeout_file    2>/dev/null
cat sd_u022.sf          >>u020_tapeout_file    2>/dev/null

lp ru020b 2>/dev/null
#lp ru020c 2>/dev/null

echo
date
echo

