#!/bin/ksh
# file: run_icu_payroll_5
#  ICU Payroll Run 5
#

echo
echo Running \'run_icu_payroll_5\'
echo
echo Upon completion - verify results in log file: \'teb_icu.log\'
echo
echo Hit ENTER to start
read garbage
echo continuing ...

rm teb_icu.log 1>/dev/null 2>&1

echo "ICU Payroll Run 5 - starting - `date`" > teb_icu.log

echo "--- generate_icu_payroll ---"         >> teb_icu.log
$cmd/generate_icu_payroll 200305 200301     >> teb_icu.log 2>&1

echo "--- u090f (QTP RUN) ---" 		    >> teb_icu.log
qtp auto=$obj/u090f.qtc 		    >> teb_icu.log 2>&1

echo "ICU - Payroll Run 5 - ending - `date`">> teb_icu.log
