#!/bin/ksh
#file: 81y2k_reports 
# 00/???/?? M.C. - original
# 01/feb/15 B.E. - enhancments to u933 and changes in subfile names
# 01/apr/25 B.E. - runs u933a_part1 instead of u933

echo Running \'81y2k_reports\'
echo 
echo NOTE: Run \'generate_81y2k_payroll\' in \'ICU Payroll Environment\' 
echo       after this process completes
echo

# ensure running in correct environment
if [ `pwd` != /alpha/rmabill/rmabill101c/production/81 ]
then
  echo "ERROR - you are in the wrong location to run this macro"
  echo This macro must be run from the following directory:
  echo /alpha/rmabill/rmabill101c/production/81
else

echo 

echo
echo
echo  Starting run ..... `date "+%T"`
rm f119.sf* 1>/dev/null 2<&1

echo  create icu-app-file
echo 

rm   icu_app_file.dat icu_app_file_explode.dat 	1>/dev/null 2>&1 

echo "Creating icu-app-file ..."
echo " "
qutil << QUTIL_EXIT
create file icu-app-file
create file icu-app-file-explode
QUTIL_EXIT

rm  icuapp.sf* u933a.sf* u933a.sf*	1>/dev/null 2>&1 
rm  r934*.txt				1>/dev/null 2>&1 

echo "Running u931_temp ..."
echo " "
qtp auto=$obj/u931_temp.qtc

rm  qkin.txt qkout.txt qkecho.txt	1>/dev/null 2>&1 

touch qkin.txt
touch qkout.txt
touch qkecho.txt

#quick auto=$obj/icuapp.qkg term=d410 notermpoll
echo "Running m932.qkc ..."
echo " "
quick auto=$obj/m932.qkc term=vt100

qtp  auto=$obj/u933a_part1.qtc 

echo  Finished Time `date "+%T"`
fi
