#!/bin/ksh
#file: run_icu_reports
#
if [ `pwd` != /alpha/rmabill/rmabill101c/production/85 ]
then
  echo " ERROR - you are in the wrong location to run this macro"
  echo You must be in \'/alpha/rmabill/rmabill101c/production/85\'
else

echo
echo Running \'run_icu_reports\'
echo
echo Upon completion - check log \'icu_reports.log\' for errors!
echo 
echo NOTE: Run the appropirate \'run_icu_payroll_xx\' macro in \'ICU Payroll Environment\'  next
echo
echo
echo Hit ENTER to start
read garbage
echo continuing ...

rm icu_reports.log	1>/dev/null 2>&1

echo "ICU Reports - starting - `date`"   > icu_reports.log
$cmd/icu_reports       			>> icu_reports.log

echo "ICU Reports - ending   - `date`"	>> icu_reports.log
fi
