#!/bin/ksh
# pupose: create macro to process all files specified thru u031 and u021 pgms

rm 1>/dev/null 2>/dev/null u021.log u031.log
echo "#!/bin/ksh"						>  u021.tmp.com
echo "# this batch file auto-created by u021.com/u021.awk"	>> u021.tmp.com
echo " "                                                        >> u021.tmp.com

timeStamp=20`date +%y_%m_%d.%H:%M` ;export timeStamp


for fname in $*
do
  /macros/dy_time "Building macro for Error file .. $fname"
  awk -v timeStamp=20`date +%y_%m_%d.%H:%M` -f $cmd/u021.awk $fname < $fname 
done
chmod +x u021.tmp.com

echo
echo "Now running u021.tmp.com - VERIFY results in:  u021.log."$timeStamp".done"
echo
#echo "hit enter to continue"
#read garbage

mkdir u021_logs/$timeStamp
rm r031*.lp
./u021.tmp.com >  u021.log
cat u031.log   >> u021.log
rm  u031.log

#lpc r031*.lp 

# save run commands as backup
#mv u021.tmp.com u021_logs/u021.$timeStamp.done
#mv u021.log     u021_logs/u021.log.$timeStamp.done
mv u021.tmp.com u021_logs/$timeStamp/u021.done
mv u021.log     u021_logs/$timeStamp/u021.log.done
echo
echo Done!
