#!/bin/ksh
# purpose: create macro to process all files thru the u021 processing
# 2006/aug/17 M.C. - include new report r021a.txt
# 2013/jan/08 MC1  - include report r021bb.txt r021bc.txt r021c.txt to the u021_logs subfolder


echo recreate the empty temporary scratch file tmp-serv-err-claim

qutil << eof_qutil
create file tmp-serv-err-claim
eof_qutil


rm 1>/dev/null 2>/dev/null u021_ph.log u021_cb.log
echo "#!/bin/ksh"						>  u021.tmp.com
echo "# this batch file auto-created by u021.com/u021.awk"	>> u021.tmp.com
echo " "                                                        >> u021.tmp.com

timeStamp=20`date +%y_%m_%d.%H:%M` ;export timeStamp

rm 1>/dev/null 2>/dev/null  u021a_edt_1ht_file.dat
rm 1>/dev/null 2>/dev/null  u021a_edt_rmb_file.dat
rm 1>/dev/null 2>/dev/null  r021*.txt

for fname in $*
do
  /macros/dy_time "Building macro for Error file .. $fname"
#  awk -v timeStamp=20`date +%y_%m_%d.%H:%M` -f $cmd/u021.awk $fname < $fname 
echo    awk -v timeStamp=$timeStamp -f $cmd/u021.awk $fname < $fname 
done

