#!/bin/ksh
#file:  u140_stage5
# 08/jun/23 b.e. - original

clear
echo Running \'processing of AFP Conversion Payment file - Stage 5\'
echo 

echo 
#echo  'HIT  "NEWLINE"  TO CONTINUE'
#read garbage
echo 
echo Process now loading ... when done the log file will be paged to your screen

$cmd/u140_stage5.com $1 > u140_stage5.log
pg u140_stage5.log
