#!/bin/ksh
# "nightly" RMABILL backups 
# B.E. 98/sep/17 - changed to run at 4 AM the next morning
# B.E. 99/aug/08 - changed to run at 2 AM the next morning
# M.C. 09/feb/11 - run $cmd/backup_all_data_to_disk every day or weekly
#
#mm hh * * daysofweek 
#55 23 * * 1-5 /bin/su backprall -c "/macros/backup_rmabill_all.com > /backups/last_run.log 2>&1"
#00 02 * * 2-6 /macros/backup_rmabill_all.com > /backups/last_run.log 2>&1
# RESTORE THIS
####00 02 * * 2-6 /macros/backup_nightly_to_dyad.com > /backups/last_run.log 2>&1
##50 01 * * 2-6 /macros/backup_nightly_to_dyad.com > /backups/last_run.log 2>&1
##50 01 * * 2-6 /macros/backup_nightly_to_dyad_with_part1to3.com > /backups/last_run.log 2>&1
#---------------------------------------------------------------------------------------------------------------
#--------brad 2009/aug/28 ----> 50 01 * * 6 /macros/backup_nightly_to_dyad_with_part1to3.com > /backups/last_run.log 2>&1
#---------------------------------------------------------------------------------------------------------------
#39 10 * * 2-6 /macros/brad.com                   > /backups/last_run.log 2>&1
#06 06 * * * /alpha/rmabill/rmabill101c/cmd/update_revenue >> alpha/rmabill/rmabill101c/update_revenue.log
# 2009/APR/24 b.e. CPI dying - 4pm back and this one may be killing performance move from 6 to 7pm 
#  changed to run at 7pm -->00 18 * * 1-5 /alpha/rmabill/rmabill101c/cmd/backup_all_data_to_disk > /backups/backup_all_data_to_disk.log 2>&1
#---------------------------------------------------------------------------------------------------------------
#00 19 * * 1-5 /alpha/rmabill/rmabill101c/cmd/backup_all_data_to_disk > /backups/backup_all_data_to_disk.log 2>&1
15 19 * * 1-5 /alpha/rmabill/rmabill101c/cmd/backup_all_data_to_disk > /backups/backup_all_data_to_disk.log 2>&1
#---------------------------------------------------------------------------------------------------------------
# process patients from meditech extract after 5 minutes after each hour
#07 * * * * /bin/ksh  /alpha/rmabill/rmabill101c/cmd/run_meditech_upload >> /alpha/rmabill/rmabill101c/upload/run_meditech_upload.log
# RESTORE THIS
00 01 * * * /alpha/rmabill/rmabill101c/cmd/utl0200.com >> /alpha/rmabill/rmabill101c/production/utl0200.log 2>&1
#------> 00  * * * * /macros/heartbeat.com
#------> 15  * * * * /macros/heartbeat.com
#------> 30  * * * * /macros/heartbeat.com
#------> 45  * * * * /macros/heartbeat.com
