//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rresource.Resources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Quoted is an 11 digit item.  Enter the date as day-
        ///month-year (11-JUL-1990).  This captures the date when the policy
        ///was actually invoiced. The date is automatically captured during
        ///the Invoicing process..
        /// </summary>
        public static string ACCQUOTE {
            get {
                return ResourceManager.GetString("ACCQUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is a 30 character item.  It is mandatory to enter the
        ///street &amp;  postal information.  The second line is another
        ///30 characters for continuation..
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER THE CODE CORRESPONDING TO THE ALLEGATIONS MADE IN THE CLAIM.
        ///A LIST OF VALID CODES IS AVAILABLE THROUGH A FUNCTION KEY..
        /// </summary>
        public static string ALLEGE {
            get {
                return ResourceManager.GetString("ALLEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLFIRMS update and multi-key search
        ///
        ///                   Name/Address Screen
        ///The first screen displays information about client&apos;s firm as
        ///supplied in the application.  When you add a record, a new ISN is
        ///generated automatically.  Make a note of it before clearing the
        ///screen. In Add mode, some of the items are mandatory, others have
        ///lists or defaults. The ISN will be generated and the progress
        ///record screen will follow.
        ///
        ///The progress screen(the second screen of allfirms), allows you
        ///to track the p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ALLFIRMS {
            get {
                return ResourceManager.GetString("ALLFIRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Logged is an 11 digit item.  Enter the date as day-
        ///month-year (11-JUL-1990).  BD (beginning of day) is the default
        ///value for today&apos;s date.  This captures when the application is
        ///being input in the system..
        /// </summary>
        public static string APPLOG {
            get {
                return ResourceManager.GetString("APPLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Received is an 11 digit item.  Enter the date as
        ///day-month-year (11-JUL-1990).  BD (beginning of day)is the default
        ///value for today&apos;s date.  This captures when the application was
        ///received at rma..
        /// </summary>
        public static string APPRECEV {
            get {
                return ResourceManager.GetString("APPRECEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Signed is an 11 digit item.  Enter the date as day-
        ///month-year (11-JUL-1990).   This captures when the application was
        ///signed by the firm&apos;s representative.;
        ///
        ///HELP-F49358:
        ///                      Retroactive Date:
        ///
        ///-&gt; use &apos;Jan 01 1900&apos; (bogus date) to indicate retrodate not
        ///                      applicable (i.e. full prior acts).
        ///
        ///-&gt; use &apos;           &apos; (blank) to indicate &quot;at inception&quot; when not
        ///                      covering full prior and effective date unknown.
        ///
        ///-&gt; use &apos;Xxx dd yyyy&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APPSIGN {
            get {
                return ResourceManager.GetString("APPSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Contact is a 30 character field.  Enter the full name
        ///of the Brokers to deal with for this firm&apos;s application..
        /// </summary>
        public static string BROKCONT {
            get {
                return ResourceManager.GetString("BROKCONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is a 30 character item.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER THE CODE REPRESENTING THE CLASS OF CLAIMANT HERE.
        ///A LIST OF VALID CODES IS AVAILABLE THROUGH A FUNCTION KEY..
        /// </summary>
        public static string CLASS {
            get {
                return ResourceManager.GetString("CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed is a 14 character item.  It is mandatory to enter an
        ///abbreviated version of the firm name.  It is mainly used for
        ///sorting purposes..
        /// </summary>
        public static string CONDENSE {
            get {
                return ResourceManager.GetString("CONDENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Type
        ///-----------------
        ///1 = Fire resistive
        ///2 = Masonry non-combustible
        ///3 = Non-combustible
        ///4 = Masonry
        ///5 = Masonry Veneer
        ///6 = Frame.
        /// </summary>
        public static string CONSTYPE {
            get {
                return ResourceManager.GetString("CONSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D35343 {
            get {
                return ResourceManager.GetString("D35343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D35345 {
            get {
                return ResourceManager.GetString("D35345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D35350 {
            get {
                return ResourceManager.GetString("D35350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                       Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress records are  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D35351 {
            get {
                return ResourceManager.GetString("D35351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D35352 {
            get {
                return ResourceManager.GetString("D35352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D35353 {
            get {
                return ResourceManager.GetString("D35353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D49871 {
            get {
                return ResourceManager.GetString("D49871", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D49913 {
            get {
                return ResourceManager.GetString("D49913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D49949 {
            get {
                return ResourceManager.GetString("D49949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                             Progress record
        ///This screen contains data that is pertainent to one application or
        ///renewal.  The Brokers, ISN, company contacts, status and dates help
        ///to track the application/policy.  All applications have a record.
        ///For firms with multiple applications, there is a progress record
        ///for each application.  You can flip through these records, one
        ///after another in add, mod or inquire modes.  Once one application
        ///is accepted as a policy, the other progress record [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D49990 {
            get {
                return ResourceManager.GetString("D49990", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This amount will be split between pool member companies that are
        ///charged GST.  In the case when this amount equals the total
        ///requested amount, the total is split among all pool members..
        /// </summary>
        public static string F11983 {
            get {
                return ResourceManager.GetString("F11983", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This amount will be split among pool member companies that are exempt
        ///from GST.
        ///If this amount is 0 then the total amount requested will be split
        ///among all pool members..
        /// </summary>
        public static string F11984 {
            get {
                return ResourceManager.GetString("F11984", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select all SRD programs for an alphabetic listing enter &apos;**&apos;.
        ///Otherwise enter a valid program code, or leave blank to select all
        ///programs..
        /// </summary>
        public static string F12071 {
            get {
                return ResourceManager.GetString("F12071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value updates the field &apos;this-claim-limit&quot; in the coverage table
        ///and doesn&apos;t represent the actual policy limit..
        /// </summary>
        public static string F12126 {
            get {
                return ResourceManager.GetString("F12126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the type of firm.
        ///E = Expert
        ///L = Lawyer
        ///I = Investigator/Adjuster.
        /// </summary>
        public static string F12174 {
            get {
                return ResourceManager.GetString("F12174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies if the service partner is a member of panel.
        ///
        /// P = Panel Member
        /// N = Non-Panel.
        /// </summary>
        public static string F12176 {
            get {
                return ResourceManager.GetString("F12176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the lawyer used for defence and the lawyer that
        /// determines coverage.
        ///
        /// C = Coverage
        /// D = Defence.
        /// </summary>
        public static string F12180 {
            get {
                return ResourceManager.GetString("F12180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This fields is a flag to indicate whether the endorsement is standard
        ///or mid-term.
        ///
        ///  S - indicates standard endorsement (attached at inception)
        ///  M - indicates mid-term endorsement (attached after inception)
        ///
        ///  Note that when endorsements print, mid-term endorsements get the
        ///appropriate trailer (for signatures, approvals, etc.).  Standard
        ///endorsements do not print these trailers, since they are sent along
        ///with the policy itself..
        /// </summary>
        public static string F41300 {
            get {
                return ResourceManager.GetString("F41300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following are the valid reasons for cancellation:
        ///
        ///01 - Non compliance           - cancel date is 45 days from today
        ///02 - Claim history/frequency  - cancel date is 45 days from today
        ///03 - Non payment              - cancel date is 15 days from today
        ///04 - Insured/broker request
        ///05 - Out of business
        ///06 - Limits or coverage
        ///07 - Misrepresentation
        ///08 - Placed elsewhere
        ///09 - Liability hazard
        ///10 - Poor service
        ///11 - Buy out / merge with other consultant;.
        /// </summary>
        public static string F41934 {
            get {
                return ResourceManager.GetString("F41934", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following cancel methods are valid:
        ///
        ///P = Pro-rata
        ///S = Short rate
        ///F = Flat
        ///M = Minimum retained.
        /// </summary>
        public static string F41938 {
            get {
                return ResourceManager.GetString("F41938", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S - To cancel Short Rate
        ///M - To cancel MRP.
        /// </summary>
        public static string F41945 {
            get {
                return ResourceManager.GetString("F41945", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARENT ISN  is a six digit optional field used to tie a current
        ///firm to a former firm numbers that have split or joined with
        ///other firms.
        /// </summary>
        public static string F43693 {
            get {
                return ResourceManager.GetString("F43693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIC - Difference in Conditions
        ///------------------------------
        ///
        ///Key Format: DIC-xx
        ///
        ///
        ///            where: DIC  indicates a DIC endorsement is being entered
        ///                   -xx  represents any whole number in the defined
        ///                        range of 15 thru 25, and is the rate at which
        ///                        the DIC endorsement will be offered.
        ///
        ///
        ///The key MUST be entered in this format so that subsequent
        ///premium calculations will be performed as required, and
        ///documents will be produced with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string F44837 {
            get {
                return ResourceManager.GetString("F44837", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVISION is a four character field which describes the
        ///type of Policy this firm is eligible for.
        ///
        ///Valid values for this field are:
        ///
        ///             VALUE                DESCRIPTION
        ///             -----                -----------
        ///             PRAC                 Practice Policy
        ///             FREE                 Claims Free Coverage
        ///             INDV                 Individuals.
        /// </summary>
        public static string F49404 {
            get {
                return ResourceManager.GetString("F49404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMTYPE is a four character field describing the type of activity
        ///the firm engages in.  Valid values for this field are:
        ///
        ///  VALUES           DESCRIPTION
        ///
        ///   ARCH            Architect
        ///   ENGR            Engineer
        ///   COMB            Combined (used only for DIVISION CORP).
        /// </summary>
        public static string F49405 {
            get {
                return ResourceManager.GetString("F49405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVISION is a four character field which describes the
        ///type of Policy this firm is eligible for.
        ///
        ///Valid values for this field are:
        ///
        ///             VALUE                DESCRIPTION
        ///             -----                -----------
        ///             PRAC                 Practice Policy
        ///             FREE                 Claims Free Coverage.
        /// </summary>
        public static string F49432 {
            get {
                return ResourceManager.GetString("F49432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMTYPE is a four character field describing the type of activity
        ///the firm engages in.  Valid values for this field are:
        ///
        ///  VALUES           DESCRIPTION
        ///
        ///   ARCH            Architect
        ///   ENGR            Engineer
        ///   DB              Design Build
        ///   CON             Contractors.
        /// </summary>
        public static string F49433 {
            get {
                return ResourceManager.GetString("F49433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARENT ISN  is a six digit optional field used to tie a current
        ///firm to a former firm numbers that have split or joined with
        ///other firms.
        /// </summary>
        public static string F49854 {
            get {
                return ResourceManager.GetString("F49854", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS is the state-of-being of this particular application:
        ///
        ///  STATUS      EXPLANATION
        ///  ------      --------------
        ///  CURR        Current
        ///  DEC         Declined
        ///  DQ          Dead Quotes
        ///  DECX        Declined / transfered
        ///  NEW         First year in force
        ///  OLD         Previously insured, not current
        ///  REAQ        Reaquired Business
        ///  SUBM        Submission
        ///  XFER        Transfered to another insurer
        ///  CANX        Undoled.
        /// </summary>
        public static string F49892 {
            get {
                return ResourceManager.GetString("F49892", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS is the state-of-being of this particular application:
        ///
        ///  STATUS      EXPLANATION
        ///  ------      --------------
        ///  CURR        Current
        ///  DEC         Declined
        ///  DQ          Dead Quotes
        ///  DECX        Declined / transfered
        ///  NEW         First year in force
        ///  OLD         Previously insured, not current
        ///  REAQ        Reaquired Business
        ///  SUBM        Submission
        ///  XFER        Transfered to another insurer
        ///  CANX        Undoled.
        /// </summary>
        public static string F49931 {
            get {
                return ResourceManager.GetString("F49931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS is the state-of-being of this particular application:
        ///
        ///  STATUS      EXPLANATION
        ///  ------      --------------
        ///  CURR        Current
        ///  DEC         Declined
        ///  DQ          Dead Quotes
        ///  DECX        Declined / transfered
        ///  NEW         First year in force
        ///  OLD         Previously insured, not current
        ///  REAQ        Reaquired Business
        ///  SUBM        Submission
        ///  XFER        Transfered to another insurer
        ///  CANX        Undoled.
        /// </summary>
        public static string F49970 {
            get {
                return ResourceManager.GetString("F49970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS is the state-of-being of this particular application:
        ///
        ///  STATUS      EXPLANATION
        ///  ------      --------------
        ///  CURR        Current
        ///  DEC         Declined
        ///  DQ          Dead Quotes
        ///  DECX        Declined / transfered
        ///  NEW         First year in force
        ///  OLD         Previously insured, not current
        ///  REAQ        Reaquired Business
        ///  SUBM        Submission
        ///  XFER        Transfered to another insurer
        ///  CANX        Undoled.
        /// </summary>
        public static string F50011 {
            get {
                return ResourceManager.GetString("F50011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVISION is a four character field which describes the
        ///type of Policy this firm is eligible for.
        ///
        ///Valid values for this field are:
        ///
        ///             VALUE                DESCRIPTION
        ///             -----                -----------
        ///             PRAC                 Practice Policy
        ///             FREE                 Claims Free Coverage.
        /// </summary>
        public static string F50531 {
            get {
                return ResourceManager.GetString("F50531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMTYPE is a four character required field the describes the type
        ///of activity engaged by the firm.  Valid values are:
        ///
        /// VALUE            DESCRIPTION
        ///
        /// ARCH             Architecture
        /// DB               Design Build
        /// ENGR             Engineer
        /// SURV             Surveyor
        /// COMB             Combined (used only with CORP division)
        /// CON              Contractors
        /// LAR              Landscape Architects
        /// PM               Project Managers of Construction Projects
        /// GEO              Geo Scientists
        /// SURV       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string F50532 {
            get {
                return ResourceManager.GetString("F50532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIC - Difference in Conditions
        ///------------------------------
        ///
        ///Key Format: DIC-xx
        ///
        ///
        ///            where: DIC  indicates a DIC endorsement is being entered
        ///                   -xx  represents any whole number in the defined
        ///                        range of 15 thru 25, and is the rate at which
        ///                        the DIC endorsement will be offered.
        ///
        ///
        ///The key MUST be entered in this format so that subsequent
        ///premium calculations will be performed as required, and
        ///documents will be produced with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string F51254 {
            get {
                return ResourceManager.GetString("F51254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field indicates what policy database the policy information
        ///should be retrieved from..
        /// </summary>
        public static string F6074 {
            get {
                return ResourceManager.GetString("F6074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is used to determine what line of business the
        ///program should report under.  Often the value in this field is
        ///the same as the value entered into the Database field.  However,
        ///this is not always true.  For Example, Land Surveyors retrieves
        ///policy information from the SRD Database.  However, Land Surveyors
        ///are assigned AE claim/incident numbers and report under the
        ///AE line of business.
        ///
        ///  Land Surveyor example:
        ///        Program Code    :  LS
        ///        Description     :  Land Surveyors
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string F8948 {
            get {
                return ResourceManager.GetString("F8948", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name is a 40 character item. It is mandatory to enter a name.  The second line is another 40 characters for continuation.  This is what will print in all correspondence..
        /// </summary>
        public static string FIRMNAME {
            get {
                return ResourceManager.GetString("FIRMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the following Firmtypes are valid:
        ///
        ///BR  - Builder&apos;s Risk
        ///WB  - Wood Frame
        ///WU  - Wrap Up
        ///CGL - Project Liability.
        /// </summary>
        public static string FIRMTYPE {
            get {
                return ResourceManager.GetString("FIRMTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is a one character item.  It is mandatory to enter E
        ///(English) or F (French)..
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALEXANDER HOLBURN BEAUDIN &amp; LANG LLP        L 0190   Panel
        ///BARNES TWINING &amp; SHORT                      L 0252   Non-Panel
        ///BCA CLAIMS &amp; CONSULTING LTD.                I 0037   Panel
        ///BEAUVAIS TRUCHON                            L 0315   Non-Panel
        ///BÉLANGER LONGTIN                            L 0279   Panel
        ///BORDEN LADNER GERVAIS LLP                   L 0292   Panel
        ///BROUWER CLAIMS CANADA &amp; CO. LTD.            I 0053   Non-Panel
        ///BULL HOUSSER &amp; TUPPER                       L 0078   Panel
        ///CHARLES TAYLOR ADJUS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LAWFIRM {
            get {
                return ResourceManager.GetString("LAWFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Bound is an 11 digit item.  Enter the date as day-month-
        ///year (11-JUL-1990).  This captures the date coverage was bound for
        ///a policy..
        /// </summary>
        public static string POLBOUND {
            get {
                return ResourceManager.GetString("POLBOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Mailed is an 11 digit item.  Enter the date as day-
        ///month-year (11-JUL-1990).  This captures when the policy was mailed
        ///out of the office..
        /// </summary>
        public static string POLMAIL {
            get {
                return ResourceManager.GetString("POLMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field represents the Pool Number assigned by the accounting
        ///department. There are different numbers for property and liability
        ///and also they differ depending on the layer limit. Please
        ///contact the accounting department for a valid Pool List..
        /// </summary>
        public static string POOLNUM {
            get {
                return ResourceManager.GetString("POOLNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is a 6 character item. It is set to receive
        ///Canadian codes. Enter the code as letter/digit/letter/space/
        ///digit/letter/digit..
        /// </summary>
        public static string POSTCODE {
            get {
                return ResourceManager.GetString("POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB    Alberta
        ///BC    British Columbia
        ///MB    Manitoba
        ///NB    New Brunswick
        ///NF    Newfoundland
        ///NS    Nova Scotia
        ///NT    Northwest Territories
        ///NU    Nunavut
        ///ON    Ontario
        ///PE    Prince Edward Island
        ///PQ    Quebec
        ///SK    Saskatchewan
        ///YT    Yukon Territories.
        /// </summary>
        public static string PROVINCE {
            get {
                return ResourceManager.GetString("PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Quoted is an 11 digit item.  Enter the date as day-month-
        ///year (11-JUL-1990).  This captures when the quote was first quoted..
        /// </summary>
        public static string QUOTMAIL {
            get {
                return ResourceManager.GetString("QUOTMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated is an 11 digit item.  Enter the date as day-month-year
        ///(11-JUL-1990).  This captures when the quote was estimated in the
        ///Underwriting group.  It&apos;s automatically updated the 1st time
        ///through rating and it can be modified manually by the underwriter..
        /// </summary>
        public static string RATED {
            get {
                return ResourceManager.GetString("RATED", resourceCulture);
            }
        }
    }
}
